// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rafiki/daraja/v1/daraja.proto

package darajapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind names the child protocol daraja is hosting. daraja's RELAY is entirely
// protocol-blind; only its spawn path consults this, to pick an argv builder.
// A second stdio kind is therefore additive rather than a breaking change.
type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	Kind_KIND_CLAUDE      Kind = 1
	// KIND_SCRIPT hosts a saved pymodule run. Only the spawn path consults the
	// kind (to pick the resolution and disable respawn); the relay is blind.
	Kind_KIND_SCRIPT Kind = 2
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_CLAUDE",
		2: "KIND_SCRIPT",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_CLAUDE":      1,
		"KIND_SCRIPT":      2,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_rafiki_daraja_v1_daraja_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_rafiki_daraja_v1_daraja_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{0}
}

type RelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bytes to write to the child's stdin, verbatim. No framing is imposed: the
	// child's protocol is the caller's business.
	Stdin         []byte `protobuf:"bytes,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type RelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RelayResponse_Stdout
	//	*RelayResponse_Restarted
	//	*RelayResponse_Exited
	//	*RelayResponse_Stderr
	Event         isRelayResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetEvent() isRelayResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RelayResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Event.(*RelayResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *RelayResponse) GetRestarted() *ProcessRestarted {
	if x != nil {
		if x, ok := x.Event.(*RelayResponse_Restarted); ok {
			return x.Restarted
		}
	}
	return nil
}

func (x *RelayResponse) GetExited() *ProcessExited {
	if x != nil {
		if x, ok := x.Event.(*RelayResponse_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *RelayResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Event.(*RelayResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

type isRelayResponse_Event interface {
	isRelayResponse_Event()
}

type RelayResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type RelayResponse_Restarted struct {
	Restarted *ProcessRestarted `protobuf:"bytes,2,opt,name=restarted,proto3,oneof"`
}

type RelayResponse_Exited struct {
	Exited *ProcessExited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"`
}

type RelayResponse_Stderr struct {
	// stderr relays the child's standard error. Claude's is discarded
	// (its protocol is stdout); a script's stderr is load-bearing — the
	// daemon keeps the tail and a failed run's settle carries it. One arm
	// per stream direction keeps both byte streams ordered within their own
	// channel, which is all either consumer reads.
	Stderr []byte `protobuf:"bytes,4,opt,name=stderr,proto3,oneof"`
}

func (*RelayResponse_Stdout) isRelayResponse_Event() {}

func (*RelayResponse_Restarted) isRelayResponse_Event() {}

func (*RelayResponse_Exited) isRelayResponse_Event() {}

func (*RelayResponse_Stderr) isRelayResponse_Event() {}

// ProcessRestarted marks the boundary between one child process's output and
// its replacement's, IN the byte stream.
//
// It is load-bearing rather than informational. A consumer that translates the
// child's output holds per-process state, and a replacement process starts that
// state over. Without an in-band marker the consumer cannot tell where to reset
// and carries stale state into the new process — which presents as a hung
// child, not as an error.
type ProcessRestarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRestarted) Reset() {
	*x = ProcessRestarted{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRestarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRestarted) ProtoMessage() {}

func (x *ProcessRestarted) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRestarted.ProtoReflect.Descriptor instead.
func (*ProcessRestarted) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessRestarted) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessExited struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is 0 for a signalled process, which is reported in signal
	// instead; -1 means the outcome could not be determined.
	ExitCode      int32  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signal        string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessExited) Reset() {
	*x = ProcessExited{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessExited) ProtoMessage() {}

func (x *ProcessExited) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessExited.ProtoReflect.Descriptor instead.
func (*ProcessExited) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ProcessExited) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type ClaudeParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Model string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// resume_session is the claude session id to continue. It is the whole
	// recovery story: a daraja and its child are disposable precisely because
	// this id is a persisted column on conversations.child, so a replacement can
	// always pick the conversation back up.
	ResumeSession  string `protobuf:"bytes,2,opt,name=resume_session,json=resumeSession,proto3" json:"resume_session,omitempty"`
	PermissionMode string `protobuf:"bytes,3,opt,name=permission_mode,json=permissionMode,proto3" json:"permission_mode,omitempty"`
	// proxy_url points the child at rafiki's proxy face instead of Anthropic
	// directly. Empty means unproxied — daraja passes the environment through
	// unmodified, exactly as before these fields existed.
	ProxyUrl string `protobuf:"bytes,4,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	// proxy_token authenticates to proxy_url. Travels here (an authenticated
	// RPC, unlike argv) but must never reach the daraja subprocess's OWN argv —
	// AdminService.Launch puts it in that process's environment instead, the
	// same treatment the launch ticket already gets, for the same reason (ps
	// is world-readable).
	ProxyToken string `protobuf:"bytes,5,opt,name=proxy_token,json=proxyToken,proto3" json:"proxy_token,omitempty"`
	// passthrough_auth omits ANTHROPIC_AUTH_TOKEN so Claude Code's own OAuth
	// subscription credential is used instead of rafiki's proxy token. rafikid
	// resolves the auto/on/off tri-state to this single bool before sending it
	// — daraja stays dumb and carries no policy of its own.
	PassthroughAuth bool `protobuf:"varint,6,opt,name=passthrough_auth,json=passthroughAuth,proto3" json:"passthrough_auth,omitempty"`
	// auto_compact_window overrides Claude Code's assumed context size for a
	// proxied model it cannot otherwise verify. Zero leaves its default alone.
	AutoCompactWindow int32 `protobuf:"varint,7,opt,name=auto_compact_window,json=autoCompactWindow,proto3" json:"auto_compact_window,omitempty"`
	// record_requests asks the proxy to persist this conversation's raw HTTP
	// traffic (X-Rafiki-Record-Requests), mirroring the local-subprocess path's
	// same request-level opt-in.
	RecordRequests bool `protobuf:"varint,8,opt,name=record_requests,json=recordRequests,proto3" json:"record_requests,omitempty"`
	// append_system_prompt and extra_args are NOT launch-only, unlike the block
	// above: daraja rebuilds argv on every Restart, so both are re-read each
	// time. A field absent from this message is a flag silently dropped for
	// every child spawned through an executor pool.
	AppendSystemPrompt string `protobuf:"bytes,9,opt,name=append_system_prompt,json=appendSystemPrompt,proto3" json:"append_system_prompt,omitempty"`
	// extra_args is the operator escape hatch, appended last so it can override
	// anything above it, matching the local-subprocess path's convention.
	ExtraArgs []string `protobuf:"bytes,10,rep,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`
	// mcp_token is the per-child secret the injected MCP config authenticates
	// with. Same handling constraint as proxy_token above: it travels over this
	// authenticated RPC and then into the daraja process's ENVIRONMENT via
	// AdminService.Launch, and must never reach any argv, because ps is
	// world-readable. Launch-only, like proxy_token.
	McpToken      string `protobuf:"bytes,11,opt,name=mcp_token,json=mcpToken,proto3" json:"mcp_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaudeParams) Reset() {
	*x = ClaudeParams{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaudeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaudeParams) ProtoMessage() {}

func (x *ClaudeParams) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaudeParams.ProtoReflect.Descriptor instead.
func (*ClaudeParams) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{4}
}

func (x *ClaudeParams) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ClaudeParams) GetResumeSession() string {
	if x != nil {
		return x.ResumeSession
	}
	return ""
}

func (x *ClaudeParams) GetPermissionMode() string {
	if x != nil {
		return x.PermissionMode
	}
	return ""
}

func (x *ClaudeParams) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *ClaudeParams) GetProxyToken() string {
	if x != nil {
		return x.ProxyToken
	}
	return ""
}

func (x *ClaudeParams) GetPassthroughAuth() bool {
	if x != nil {
		return x.PassthroughAuth
	}
	return false
}

func (x *ClaudeParams) GetAutoCompactWindow() int32 {
	if x != nil {
		return x.AutoCompactWindow
	}
	return 0
}

func (x *ClaudeParams) GetRecordRequests() bool {
	if x != nil {
		return x.RecordRequests
	}
	return false
}

func (x *ClaudeParams) GetAppendSystemPrompt() string {
	if x != nil {
		return x.AppendSystemPrompt
	}
	return ""
}

func (x *ClaudeParams) GetExtraArgs() []string {
	if x != nil {
		return x.ExtraArgs
	}
	return nil
}

func (x *ClaudeParams) GetMcpToken() string {
	if x != nil {
		return x.McpToken
	}
	return ""
}

// ScriptParams is the script variant of a ChildSpec: a saved pymodule run
// hosted on the executor the way pymodule_run runs one.
//
// Unlike ClaudeParams, nothing here names a binary or a path: the EXECUTOR
// resolves the script against its own synced pymodule cache at Launch time —
// the same layout SyncPyModules (blob modules, with per-module venvs) and
// SyncPyModuleGitSource (checkouts) produce — and hands daraja the resolved
// interpreter and argv. The daemon never ships code to an executor it did not
// already sync, and the executor never runs code its cache does not hold.
//
// A script child is never Restarted and never respawned: a script's exit is
// its result. daraja's respawn loop is disabled for this kind.
type ScriptParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repo names the pymodule source: "local" for the owner's synced blob
	// modules (pymodule_put), or a registered git source's name for its synced
	// checkout. Resolved on the executor; an unsynced name is a Launch refusal,
	// not a runtime surprise.
	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	// script is the pymodule/script name to run — a bare Python identifier.
	Script string `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	// modules names further pymodules the script imports, resolved within the
	// same repo and joined to PYTHONPATH in call order.
	Modules []string `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	// args are the script's own command-line arguments, passed verbatim.
	Args []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// env is the spawn's forwarded environment (--forward-env). The daemon
	// strips every RAFIKI_*/ANTHROPIC_*/OPENROUTER_* variable before sending
	// (a forwarded credential must not resurrect what the strip removed) and
	// the executor strips again before applying — same rule, both planes.
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// child_secret is the per-child Connect credential the executor's per-child
	// socket (pkg/childsock) injects as the Authorization bearer on everything
	// the script sends the daemon. LAUNCH-ONLY, like proxy_token/mcp_token: it
	// travels this authenticated RPC and then into the daraja process's
	// environment (RAFIKI_CHILD_SECRET, set by AdminService.Launch) — never any
	// argv, because ps is world-readable — and it is held in memory only. The
	// script itself never sees it: its RAFIKI_CHILD_CONNECT names a socket, not
	// a token.
	ChildSecret   string `protobuf:"bytes,6,opt,name=child_secret,json=childSecret,proto3" json:"child_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptParams) Reset() {
	*x = ScriptParams{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptParams) ProtoMessage() {}

func (x *ScriptParams) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptParams.ProtoReflect.Descriptor instead.
func (*ScriptParams) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{5}
}

func (x *ScriptParams) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ScriptParams) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ScriptParams) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ScriptParams) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ScriptParams) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ScriptParams) GetChildSecret() string {
	if x != nil {
		return x.ChildSecret
	}
	return ""
}

// ChildSpec is everything needed to (re)build the child's command line.
//
// Typed rather than raw argv because the executor's Launch and daraja's Restart
// would otherwise each need an argv builder, on opposite sides of an RPC. Both
// call pkg/claudeargv instead.
//
// Exactly one variant is set. For kind SCRIPT the executor resolves
// ScriptParams against its synced cache before starting daraja; a Restart of a
// script child is refused semantically (a script's exit is its result), so the
// wire spec never needs to rebuild a script's resolved argv.
type ChildSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=rafiki.daraja.v1.Kind" json:"kind,omitempty"`
	Claude        *ClaudeParams          `protobuf:"bytes,2,opt,name=claude,proto3" json:"claude,omitempty"`
	Script        *ScriptParams          `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildSpec) Reset() {
	*x = ChildSpec{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildSpec) ProtoMessage() {}

func (x *ChildSpec) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildSpec.ProtoReflect.Descriptor instead.
func (*ChildSpec) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{6}
}

func (x *ChildSpec) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *ChildSpec) GetClaude() *ClaudeParams {
	if x != nil {
		return x.Claude
	}
	return nil
}

func (x *ChildSpec) GetScript() *ScriptParams {
	if x != nil {
		return x.Script
	}
	return nil
}

type RestartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// spec replaces the child. When absent, daraja reuses the spec it currently
	// holds — which is how a caller restarts without restating everything it
	// already knows.
	Spec *ChildSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// grace_ms to wait after the interrupt before escalating to a hard kill.
	// Zero means the server default.
	GraceMs       int32 `protobuf:"varint,2,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{7}
}

func (x *RestartRequest) GetSpec() *ChildSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RestartRequest) GetGraceMs() int32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type RestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{8}
}

func (x *RestartResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceMs       int32                  `protobuf:"varint,1,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{9}
}

func (x *ShutdownRequest) GetGraceMs() int32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{10}
}

func (x *ShutdownResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ShutdownResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_daraja_v1_daraja_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_rafiki_daraja_v1_daraja_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *HealthResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

var File_rafiki_daraja_v1_daraja_proto protoreflect.FileDescriptor

const file_rafiki_daraja_v1_daraja_proto_rawDesc = "" +
	"\n" +
	"\x1drafiki/daraja/v1/daraja.proto\x12\x10rafiki.daraja.v1\"$\n" +
	"\fRelayRequest\x12\x14\n" +
	"\x05stdin\x18\x01 \x01(\fR\x05stdin\"\xcb\x01\n" +
	"\rRelayResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12B\n" +
	"\trestarted\x18\x02 \x01(\v2\".rafiki.daraja.v1.ProcessRestartedH\x00R\trestarted\x129\n" +
	"\x06exited\x18\x03 \x01(\v2\x1f.rafiki.daraja.v1.ProcessExitedH\x00R\x06exited\x12\x18\n" +
	"\x06stderr\x18\x04 \x01(\fH\x00R\x06stderrB\a\n" +
	"\x05event\"$\n" +
	"\x10ProcessRestarted\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"D\n" +
	"\rProcessExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\xa4\x03\n" +
	"\fClaudeParams\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12%\n" +
	"\x0eresume_session\x18\x02 \x01(\tR\rresumeSession\x12'\n" +
	"\x0fpermission_mode\x18\x03 \x01(\tR\x0epermissionMode\x12\x1b\n" +
	"\tproxy_url\x18\x04 \x01(\tR\bproxyUrl\x12\x1f\n" +
	"\vproxy_token\x18\x05 \x01(\tR\n" +
	"proxyToken\x12)\n" +
	"\x10passthrough_auth\x18\x06 \x01(\bR\x0fpassthroughAuth\x12.\n" +
	"\x13auto_compact_window\x18\a \x01(\x05R\x11autoCompactWindow\x12'\n" +
	"\x0frecord_requests\x18\b \x01(\bR\x0erecordRequests\x120\n" +
	"\x14append_system_prompt\x18\t \x01(\tR\x12appendSystemPrompt\x12\x1d\n" +
	"\n" +
	"extra_args\x18\n" +
	" \x03(\tR\textraArgs\x12\x1b\n" +
	"\tmcp_token\x18\v \x01(\tR\bmcpToken\"\xfe\x01\n" +
	"\fScriptParams\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12\x18\n" +
	"\amodules\x18\x03 \x03(\tR\amodules\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x129\n" +
	"\x03env\x18\x05 \x03(\v2'.rafiki.daraja.v1.ScriptParams.EnvEntryR\x03env\x12!\n" +
	"\fchild_secret\x18\x06 \x01(\tR\vchildSecret\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\tChildSpec\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.rafiki.daraja.v1.KindR\x04kind\x126\n" +
	"\x06claude\x18\x02 \x01(\v2\x1e.rafiki.daraja.v1.ClaudeParamsR\x06claude\x126\n" +
	"\x06script\x18\x03 \x01(\v2\x1e.rafiki.daraja.v1.ScriptParamsR\x06script\"\\\n" +
	"\x0eRestartRequest\x12/\n" +
	"\x04spec\x18\x01 \x01(\v2\x1b.rafiki.daraja.v1.ChildSpecR\x04spec\x12\x19\n" +
	"\bgrace_ms\x18\x02 \x01(\x05R\agraceMs\"#\n" +
	"\x0fRestartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\",\n" +
	"\x0fShutdownRequest\x12\x19\n" +
	"\bgrace_ms\x18\x01 \x01(\x05R\agraceMs\"G\n" +
	"\x10ShutdownResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\x0f\n" +
	"\rHealthRequest\"<\n" +
	"\x0eHealthResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning*>\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vKIND_CLAUDE\x10\x01\x12\x0f\n" +
	"\vKIND_SCRIPT\x10\x022\xcd\x02\n" +
	"\rDarajaService\x12L\n" +
	"\x05Relay\x12\x1e.rafiki.daraja.v1.RelayRequest\x1a\x1f.rafiki.daraja.v1.RelayResponse(\x010\x01\x12N\n" +
	"\aRestart\x12 .rafiki.daraja.v1.RestartRequest\x1a!.rafiki.daraja.v1.RestartResponse\x12Q\n" +
	"\bShutdown\x12!.rafiki.daraja.v1.ShutdownRequest\x1a\".rafiki.daraja.v1.ShutdownResponse\x12K\n" +
	"\x06Health\x12\x1f.rafiki.daraja.v1.HealthRequest\x1a .rafiki.daraja.v1.HealthResponseB/Z-go.graveland.dev/rafiki/pkg/darajapb;darajapbb\x06proto3"

var (
	file_rafiki_daraja_v1_daraja_proto_rawDescOnce sync.Once
	file_rafiki_daraja_v1_daraja_proto_rawDescData []byte
)

func file_rafiki_daraja_v1_daraja_proto_rawDescGZIP() []byte {
	file_rafiki_daraja_v1_daraja_proto_rawDescOnce.Do(func() {
		file_rafiki_daraja_v1_daraja_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rafiki_daraja_v1_daraja_proto_rawDesc), len(file_rafiki_daraja_v1_daraja_proto_rawDesc)))
	})
	return file_rafiki_daraja_v1_daraja_proto_rawDescData
}

var file_rafiki_daraja_v1_daraja_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rafiki_daraja_v1_daraja_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rafiki_daraja_v1_daraja_proto_goTypes = []any{
	(Kind)(0),                // 0: rafiki.daraja.v1.Kind
	(*RelayRequest)(nil),     // 1: rafiki.daraja.v1.RelayRequest
	(*RelayResponse)(nil),    // 2: rafiki.daraja.v1.RelayResponse
	(*ProcessRestarted)(nil), // 3: rafiki.daraja.v1.ProcessRestarted
	(*ProcessExited)(nil),    // 4: rafiki.daraja.v1.ProcessExited
	(*ClaudeParams)(nil),     // 5: rafiki.daraja.v1.ClaudeParams
	(*ScriptParams)(nil),     // 6: rafiki.daraja.v1.ScriptParams
	(*ChildSpec)(nil),        // 7: rafiki.daraja.v1.ChildSpec
	(*RestartRequest)(nil),   // 8: rafiki.daraja.v1.RestartRequest
	(*RestartResponse)(nil),  // 9: rafiki.daraja.v1.RestartResponse
	(*ShutdownRequest)(nil),  // 10: rafiki.daraja.v1.ShutdownRequest
	(*ShutdownResponse)(nil), // 11: rafiki.daraja.v1.ShutdownResponse
	(*HealthRequest)(nil),    // 12: rafiki.daraja.v1.HealthRequest
	(*HealthResponse)(nil),   // 13: rafiki.daraja.v1.HealthResponse
	nil,                      // 14: rafiki.daraja.v1.ScriptParams.EnvEntry
}
var file_rafiki_daraja_v1_daraja_proto_depIdxs = []int32{
	3,  // 0: rafiki.daraja.v1.RelayResponse.restarted:type_name -> rafiki.daraja.v1.ProcessRestarted
	4,  // 1: rafiki.daraja.v1.RelayResponse.exited:type_name -> rafiki.daraja.v1.ProcessExited
	14, // 2: rafiki.daraja.v1.ScriptParams.env:type_name -> rafiki.daraja.v1.ScriptParams.EnvEntry
	0,  // 3: rafiki.daraja.v1.ChildSpec.kind:type_name -> rafiki.daraja.v1.Kind
	5,  // 4: rafiki.daraja.v1.ChildSpec.claude:type_name -> rafiki.daraja.v1.ClaudeParams
	6,  // 5: rafiki.daraja.v1.ChildSpec.script:type_name -> rafiki.daraja.v1.ScriptParams
	7,  // 6: rafiki.daraja.v1.RestartRequest.spec:type_name -> rafiki.daraja.v1.ChildSpec
	1,  // 7: rafiki.daraja.v1.DarajaService.Relay:input_type -> rafiki.daraja.v1.RelayRequest
	8,  // 8: rafiki.daraja.v1.DarajaService.Restart:input_type -> rafiki.daraja.v1.RestartRequest
	10, // 9: rafiki.daraja.v1.DarajaService.Shutdown:input_type -> rafiki.daraja.v1.ShutdownRequest
	12, // 10: rafiki.daraja.v1.DarajaService.Health:input_type -> rafiki.daraja.v1.HealthRequest
	2,  // 11: rafiki.daraja.v1.DarajaService.Relay:output_type -> rafiki.daraja.v1.RelayResponse
	9,  // 12: rafiki.daraja.v1.DarajaService.Restart:output_type -> rafiki.daraja.v1.RestartResponse
	11, // 13: rafiki.daraja.v1.DarajaService.Shutdown:output_type -> rafiki.daraja.v1.ShutdownResponse
	13, // 14: rafiki.daraja.v1.DarajaService.Health:output_type -> rafiki.daraja.v1.HealthResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rafiki_daraja_v1_daraja_proto_init() }
func file_rafiki_daraja_v1_daraja_proto_init() {
	if File_rafiki_daraja_v1_daraja_proto != nil {
		return
	}
	file_rafiki_daraja_v1_daraja_proto_msgTypes[1].OneofWrappers = []any{
		(*RelayResponse_Stdout)(nil),
		(*RelayResponse_Restarted)(nil),
		(*RelayResponse_Exited)(nil),
		(*RelayResponse_Stderr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rafiki_daraja_v1_daraja_proto_rawDesc), len(file_rafiki_daraja_v1_daraja_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rafiki_daraja_v1_daraja_proto_goTypes,
		DependencyIndexes: file_rafiki_daraja_v1_daraja_proto_depIdxs,
		EnumInfos:         file_rafiki_daraja_v1_daraja_proto_enumTypes,
		MessageInfos:      file_rafiki_daraja_v1_daraja_proto_msgTypes,
	}.Build()
	File_rafiki_daraja_v1_daraja_proto = out.File
	file_rafiki_daraja_v1_daraja_proto_goTypes = nil
	file_rafiki_daraja_v1_daraja_proto_depIdxs = nil
}
