// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: daraja.proto

package darajapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bytes to write to the child's stdin, verbatim. No framing is imposed: the
	// child's protocol is the caller's business.
	Stdin         []byte `protobuf:"bytes,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_daraja_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type RelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RelayResponse_Stdout
	//	*RelayResponse_Restarted
	//	*RelayResponse_Exited
	Event         isRelayResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_daraja_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetEvent() isRelayResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RelayResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Event.(*RelayResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *RelayResponse) GetRestarted() *ProcessRestarted {
	if x != nil {
		if x, ok := x.Event.(*RelayResponse_Restarted); ok {
			return x.Restarted
		}
	}
	return nil
}

func (x *RelayResponse) GetExited() *ProcessExited {
	if x != nil {
		if x, ok := x.Event.(*RelayResponse_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

type isRelayResponse_Event interface {
	isRelayResponse_Event()
}

type RelayResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type RelayResponse_Restarted struct {
	Restarted *ProcessRestarted `protobuf:"bytes,2,opt,name=restarted,proto3,oneof"`
}

type RelayResponse_Exited struct {
	Exited *ProcessExited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"`
}

func (*RelayResponse_Stdout) isRelayResponse_Event() {}

func (*RelayResponse_Restarted) isRelayResponse_Event() {}

func (*RelayResponse_Exited) isRelayResponse_Event() {}

// ProcessRestarted marks the boundary between one child process's output and
// its replacement's, IN the byte stream.
//
// It is load-bearing rather than informational. A consumer that translates the
// child's output holds per-process state, and a replacement process starts that
// state over. Without an in-band marker the consumer cannot tell where to reset
// and carries stale state into the new process — which presents as a hung
// child, not as an error.
type ProcessRestarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRestarted) Reset() {
	*x = ProcessRestarted{}
	mi := &file_daraja_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRestarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRestarted) ProtoMessage() {}

func (x *ProcessRestarted) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRestarted.ProtoReflect.Descriptor instead.
func (*ProcessRestarted) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessRestarted) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessExited struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is 0 for a signalled process, which is reported in signal
	// instead; -1 means the outcome could not be determined.
	ExitCode      int32  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signal        string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessExited) Reset() {
	*x = ProcessExited{}
	mi := &file_daraja_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessExited) ProtoMessage() {}

func (x *ProcessExited) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessExited.ProtoReflect.Descriptor instead.
func (*ProcessExited) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ProcessExited) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type RestartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// argv excludes the binary itself. The caller owns argv because only it knows
	// the session to resume; daraja never invents arguments.
	Argv []string `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	// grace_ms to wait after the interrupt before escalating to a hard kill.
	// Zero means the server default.
	GraceMs       int32 `protobuf:"varint,2,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_daraja_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{4}
}

func (x *RestartRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *RestartRequest) GetGraceMs() int32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type RestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_daraja_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{5}
}

func (x *RestartResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceMs       int32                  `protobuf:"varint,1,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_daraja_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{6}
}

func (x *ShutdownRequest) GetGraceMs() int32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_daraja_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ShutdownResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_daraja_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_daraja_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daraja_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_daraja_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *HealthResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

var File_daraja_proto protoreflect.FileDescriptor

const file_daraja_proto_rawDesc = "" +
	"\n" +
	"\fdaraja.proto\x12\x10rafiki.daraja.v1\"$\n" +
	"\fRelayRequest\x12\x14\n" +
	"\x05stdin\x18\x01 \x01(\fR\x05stdin\"\xb1\x01\n" +
	"\rRelayResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12B\n" +
	"\trestarted\x18\x02 \x01(\v2\".rafiki.daraja.v1.ProcessRestartedH\x00R\trestarted\x129\n" +
	"\x06exited\x18\x03 \x01(\v2\x1f.rafiki.daraja.v1.ProcessExitedH\x00R\x06exitedB\a\n" +
	"\x05event\"$\n" +
	"\x10ProcessRestarted\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"D\n" +
	"\rProcessExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"?\n" +
	"\x0eRestartRequest\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12\x19\n" +
	"\bgrace_ms\x18\x02 \x01(\x05R\agraceMs\"#\n" +
	"\x0fRestartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\",\n" +
	"\x0fShutdownRequest\x12\x19\n" +
	"\bgrace_ms\x18\x01 \x01(\x05R\agraceMs\"G\n" +
	"\x10ShutdownResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\x0f\n" +
	"\rHealthRequest\"<\n" +
	"\x0eHealthResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning2\xcd\x02\n" +
	"\rDarajaService\x12L\n" +
	"\x05Relay\x12\x1e.rafiki.daraja.v1.RelayRequest\x1a\x1f.rafiki.daraja.v1.RelayResponse(\x010\x01\x12N\n" +
	"\aRestart\x12 .rafiki.daraja.v1.RestartRequest\x1a!.rafiki.daraja.v1.RestartResponse\x12Q\n" +
	"\bShutdown\x12!.rafiki.daraja.v1.ShutdownRequest\x1a\".rafiki.daraja.v1.ShutdownResponse\x12K\n" +
	"\x06Health\x12\x1f.rafiki.daraja.v1.HealthRequest\x1a .rafiki.daraja.v1.HealthResponseB/Z-go.graveland.dev/rafiki/pkg/darajapb;darajapbb\x06proto3"

var (
	file_daraja_proto_rawDescOnce sync.Once
	file_daraja_proto_rawDescData []byte
)

func file_daraja_proto_rawDescGZIP() []byte {
	file_daraja_proto_rawDescOnce.Do(func() {
		file_daraja_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daraja_proto_rawDesc), len(file_daraja_proto_rawDesc)))
	})
	return file_daraja_proto_rawDescData
}

var file_daraja_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_daraja_proto_goTypes = []any{
	(*RelayRequest)(nil),     // 0: rafiki.daraja.v1.RelayRequest
	(*RelayResponse)(nil),    // 1: rafiki.daraja.v1.RelayResponse
	(*ProcessRestarted)(nil), // 2: rafiki.daraja.v1.ProcessRestarted
	(*ProcessExited)(nil),    // 3: rafiki.daraja.v1.ProcessExited
	(*RestartRequest)(nil),   // 4: rafiki.daraja.v1.RestartRequest
	(*RestartResponse)(nil),  // 5: rafiki.daraja.v1.RestartResponse
	(*ShutdownRequest)(nil),  // 6: rafiki.daraja.v1.ShutdownRequest
	(*ShutdownResponse)(nil), // 7: rafiki.daraja.v1.ShutdownResponse
	(*HealthRequest)(nil),    // 8: rafiki.daraja.v1.HealthRequest
	(*HealthResponse)(nil),   // 9: rafiki.daraja.v1.HealthResponse
}
var file_daraja_proto_depIdxs = []int32{
	2, // 0: rafiki.daraja.v1.RelayResponse.restarted:type_name -> rafiki.daraja.v1.ProcessRestarted
	3, // 1: rafiki.daraja.v1.RelayResponse.exited:type_name -> rafiki.daraja.v1.ProcessExited
	0, // 2: rafiki.daraja.v1.DarajaService.Relay:input_type -> rafiki.daraja.v1.RelayRequest
	4, // 3: rafiki.daraja.v1.DarajaService.Restart:input_type -> rafiki.daraja.v1.RestartRequest
	6, // 4: rafiki.daraja.v1.DarajaService.Shutdown:input_type -> rafiki.daraja.v1.ShutdownRequest
	8, // 5: rafiki.daraja.v1.DarajaService.Health:input_type -> rafiki.daraja.v1.HealthRequest
	1, // 6: rafiki.daraja.v1.DarajaService.Relay:output_type -> rafiki.daraja.v1.RelayResponse
	5, // 7: rafiki.daraja.v1.DarajaService.Restart:output_type -> rafiki.daraja.v1.RestartResponse
	7, // 8: rafiki.daraja.v1.DarajaService.Shutdown:output_type -> rafiki.daraja.v1.ShutdownResponse
	9, // 9: rafiki.daraja.v1.DarajaService.Health:output_type -> rafiki.daraja.v1.HealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_daraja_proto_init() }
func file_daraja_proto_init() {
	if File_daraja_proto != nil {
		return
	}
	file_daraja_proto_msgTypes[1].OneofWrappers = []any{
		(*RelayResponse_Stdout)(nil),
		(*RelayResponse_Restarted)(nil),
		(*RelayResponse_Exited)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daraja_proto_rawDesc), len(file_daraja_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daraja_proto_goTypes,
		DependencyIndexes: file_daraja_proto_depIdxs,
		MessageInfos:      file_daraja_proto_msgTypes,
	}.Build()
	File_daraja_proto = out.File
	file_daraja_proto_goTypes = nil
	file_daraja_proto_depIdxs = nil
}
