// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: executor.proto

package executorpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	executorpb "go.graveland.dev/rafiki/pkg/executorpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExecutorServiceName is the fully-qualified name of the ExecutorService service.
	ExecutorServiceName = "rafiki.executor.v1.ExecutorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExecutorServiceDescribeProcedure is the fully-qualified name of the ExecutorService's Describe
	// RPC.
	ExecutorServiceDescribeProcedure = "/rafiki.executor.v1.ExecutorService/Describe"
	// ExecutorServiceHealthProcedure is the fully-qualified name of the ExecutorService's Health RPC.
	ExecutorServiceHealthProcedure = "/rafiki.executor.v1.ExecutorService/Health"
	// ExecutorServiceExecuteProcedure is the fully-qualified name of the ExecutorService's Execute RPC.
	ExecutorServiceExecuteProcedure = "/rafiki.executor.v1.ExecutorService/Execute"
	// ExecutorServiceAttachProcedure is the fully-qualified name of the ExecutorService's Attach RPC.
	ExecutorServiceAttachProcedure = "/rafiki.executor.v1.ExecutorService/Attach"
	// ExecutorServiceCancelProcedure is the fully-qualified name of the ExecutorService's Cancel RPC.
	ExecutorServiceCancelProcedure = "/rafiki.executor.v1.ExecutorService/Cancel"
	// ExecutorServiceJobOutputProcedure is the fully-qualified name of the ExecutorService's JobOutput
	// RPC.
	ExecutorServiceJobOutputProcedure = "/rafiki.executor.v1.ExecutorService/JobOutput"
	// ExecutorServiceProvisionProcedure is the fully-qualified name of the ExecutorService's Provision
	// RPC.
	ExecutorServiceProvisionProcedure = "/rafiki.executor.v1.ExecutorService/Provision"
	// ExecutorServiceReleaseProcedure is the fully-qualified name of the ExecutorService's Release RPC.
	ExecutorServiceReleaseProcedure = "/rafiki.executor.v1.ExecutorService/Release"
	// ExecutorServiceProjectContextProcedure is the fully-qualified name of the ExecutorService's
	// ProjectContext RPC.
	ExecutorServiceProjectContextProcedure = "/rafiki.executor.v1.ExecutorService/ProjectContext"
	// ExecutorServiceProjectSkillsProcedure is the fully-qualified name of the ExecutorService's
	// ProjectSkills RPC.
	ExecutorServiceProjectSkillsProcedure = "/rafiki.executor.v1.ExecutorService/ProjectSkills"
	// ExecutorServiceSkillBodyProcedure is the fully-qualified name of the ExecutorService's SkillBody
	// RPC.
	ExecutorServiceSkillBodyProcedure = "/rafiki.executor.v1.ExecutorService/SkillBody"
	// ExecutorServiceProxyProcedure is the fully-qualified name of the ExecutorService's Proxy RPC.
	ExecutorServiceProxyProcedure = "/rafiki.executor.v1.ExecutorService/Proxy"
)

// ExecutorServiceClient is a client for the rafiki.executor.v1.ExecutorService service.
type ExecutorServiceClient interface {
	Describe(context.Context, *connect.Request[executorpb.DescribeRequest]) (*connect.Response[executorpb.DescribeResponse], error)
	Health(context.Context, *connect.Request[executorpb.HealthRequest]) (*connect.Response[executorpb.HealthResponse], error)
	Execute(context.Context, *connect.Request[executorpb.ExecuteRequest]) (*connect.ServerStreamForClient[executorpb.ExecuteResponse], error)
	Attach(context.Context, *connect.Request[executorpb.AttachRequest]) (*connect.ServerStreamForClient[executorpb.AttachResponse], error)
	Cancel(context.Context, *connect.Request[executorpb.CancelRequest]) (*connect.Response[executorpb.CancelResponse], error)
	JobOutput(context.Context, *connect.Request[executorpb.JobOutputRequest]) (*connect.Response[executorpb.JobOutputResponse], error)
	// Provision prepares a workspace for one child and returns a handle every
	// later Execute carries. A native executor answers with its pinned root and
	// does nothing else; a container executor starts a container.
	Provision(context.Context, *connect.Request[executorpb.ProvisionRequest]) (*connect.Response[executorpb.ProvisionResponse], error)
	// Release tears a workspace down. Idempotent: a daemon restart that lost
	// track of a workspace must be able to release it again without error.
	Release(context.Context, *connect.Request[executorpb.ReleaseRequest]) (*connect.Response[executorpb.ReleaseResponse], error)
	// ProjectContext returns the instruction files belonging to a workspace:
	// CLAUDE.md and AGENTS.md at the git root and at the workdir, with @includes
	// already expanded.
	//
	// It is a separate call rather than a field on ProvisionResponse because it
	// returns CONTENT, and content is unbounded where a workspace handle is not:
	// a large CLAUDE.md would make every provision pay for it. It is separate
	// from Describe for a different reason — Describe is per-EXECUTOR and this is
	// per-workspace, so Describe structurally cannot answer it.
	ProjectContext(context.Context, *connect.Request[executorpb.ProjectContextRequest]) (*connect.Response[executorpb.ProjectContextResponse], error)
	// ProjectSkills returns the skills discovered in a workspace — the project
	// tier only. User and system skills belong to whoever runs the agent loop and
	// are never reported here.
	//
	// Metadata only. Bodies are fetched by SkillBody on the turn a model actually
	// asks for one: an inventory is a handful of lines per skill, while a body is
	// a document, and returning every body at spawn would put the whole project's
	// skill text into every child.
	ProjectSkills(context.Context, *connect.Request[executorpb.ProjectSkillsRequest]) (*connect.Response[executorpb.ProjectSkillsResponse], error)
	// SkillBody returns one project skill's body, resolved by NAME against the
	// executor's own discovery.
	//
	// By name and not by path, for the same reason ProjectContext takes a
	// workspace id: a path parameter would let anything that reaches this
	// executor read an arbitrary file on it.
	SkillBody(context.Context, *connect.Request[executorpb.SkillBodyRequest]) (*connect.Response[executorpb.SkillBodyResponse], error)
	// Proxy relays one HTTP request to a pre-declared LLM endpoint and streams
	// the response back. One stream per request/response cycle.
	Proxy(context.Context) *connect.BidiStreamForClient[executorpb.ProxyRequest, executorpb.ProxyResponse]
}

// NewExecutorServiceClient constructs a client for the rafiki.executor.v1.ExecutorService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecutorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecutorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	executorServiceMethods := executorpb.File_executor_proto.Services().ByName("ExecutorService").Methods()
	return &executorServiceClient{
		describe: connect.NewClient[executorpb.DescribeRequest, executorpb.DescribeResponse](
			httpClient,
			baseURL+ExecutorServiceDescribeProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Describe")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[executorpb.HealthRequest, executorpb.HealthResponse](
			httpClient,
			baseURL+ExecutorServiceHealthProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		execute: connect.NewClient[executorpb.ExecuteRequest, executorpb.ExecuteResponse](
			httpClient,
			baseURL+ExecutorServiceExecuteProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
		attach: connect.NewClient[executorpb.AttachRequest, executorpb.AttachResponse](
			httpClient,
			baseURL+ExecutorServiceAttachProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Attach")),
			connect.WithClientOptions(opts...),
		),
		cancel: connect.NewClient[executorpb.CancelRequest, executorpb.CancelResponse](
			httpClient,
			baseURL+ExecutorServiceCancelProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Cancel")),
			connect.WithClientOptions(opts...),
		),
		jobOutput: connect.NewClient[executorpb.JobOutputRequest, executorpb.JobOutputResponse](
			httpClient,
			baseURL+ExecutorServiceJobOutputProcedure,
			connect.WithSchema(executorServiceMethods.ByName("JobOutput")),
			connect.WithClientOptions(opts...),
		),
		provision: connect.NewClient[executorpb.ProvisionRequest, executorpb.ProvisionResponse](
			httpClient,
			baseURL+ExecutorServiceProvisionProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Provision")),
			connect.WithClientOptions(opts...),
		),
		release: connect.NewClient[executorpb.ReleaseRequest, executorpb.ReleaseResponse](
			httpClient,
			baseURL+ExecutorServiceReleaseProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Release")),
			connect.WithClientOptions(opts...),
		),
		projectContext: connect.NewClient[executorpb.ProjectContextRequest, executorpb.ProjectContextResponse](
			httpClient,
			baseURL+ExecutorServiceProjectContextProcedure,
			connect.WithSchema(executorServiceMethods.ByName("ProjectContext")),
			connect.WithClientOptions(opts...),
		),
		projectSkills: connect.NewClient[executorpb.ProjectSkillsRequest, executorpb.ProjectSkillsResponse](
			httpClient,
			baseURL+ExecutorServiceProjectSkillsProcedure,
			connect.WithSchema(executorServiceMethods.ByName("ProjectSkills")),
			connect.WithClientOptions(opts...),
		),
		skillBody: connect.NewClient[executorpb.SkillBodyRequest, executorpb.SkillBodyResponse](
			httpClient,
			baseURL+ExecutorServiceSkillBodyProcedure,
			connect.WithSchema(executorServiceMethods.ByName("SkillBody")),
			connect.WithClientOptions(opts...),
		),
		proxy: connect.NewClient[executorpb.ProxyRequest, executorpb.ProxyResponse](
			httpClient,
			baseURL+ExecutorServiceProxyProcedure,
			connect.WithSchema(executorServiceMethods.ByName("Proxy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// executorServiceClient implements ExecutorServiceClient.
type executorServiceClient struct {
	describe       *connect.Client[executorpb.DescribeRequest, executorpb.DescribeResponse]
	health         *connect.Client[executorpb.HealthRequest, executorpb.HealthResponse]
	execute        *connect.Client[executorpb.ExecuteRequest, executorpb.ExecuteResponse]
	attach         *connect.Client[executorpb.AttachRequest, executorpb.AttachResponse]
	cancel         *connect.Client[executorpb.CancelRequest, executorpb.CancelResponse]
	jobOutput      *connect.Client[executorpb.JobOutputRequest, executorpb.JobOutputResponse]
	provision      *connect.Client[executorpb.ProvisionRequest, executorpb.ProvisionResponse]
	release        *connect.Client[executorpb.ReleaseRequest, executorpb.ReleaseResponse]
	projectContext *connect.Client[executorpb.ProjectContextRequest, executorpb.ProjectContextResponse]
	projectSkills  *connect.Client[executorpb.ProjectSkillsRequest, executorpb.ProjectSkillsResponse]
	skillBody      *connect.Client[executorpb.SkillBodyRequest, executorpb.SkillBodyResponse]
	proxy          *connect.Client[executorpb.ProxyRequest, executorpb.ProxyResponse]
}

// Describe calls rafiki.executor.v1.ExecutorService.Describe.
func (c *executorServiceClient) Describe(ctx context.Context, req *connect.Request[executorpb.DescribeRequest]) (*connect.Response[executorpb.DescribeResponse], error) {
	return c.describe.CallUnary(ctx, req)
}

// Health calls rafiki.executor.v1.ExecutorService.Health.
func (c *executorServiceClient) Health(ctx context.Context, req *connect.Request[executorpb.HealthRequest]) (*connect.Response[executorpb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// Execute calls rafiki.executor.v1.ExecutorService.Execute.
func (c *executorServiceClient) Execute(ctx context.Context, req *connect.Request[executorpb.ExecuteRequest]) (*connect.ServerStreamForClient[executorpb.ExecuteResponse], error) {
	return c.execute.CallServerStream(ctx, req)
}

// Attach calls rafiki.executor.v1.ExecutorService.Attach.
func (c *executorServiceClient) Attach(ctx context.Context, req *connect.Request[executorpb.AttachRequest]) (*connect.ServerStreamForClient[executorpb.AttachResponse], error) {
	return c.attach.CallServerStream(ctx, req)
}

// Cancel calls rafiki.executor.v1.ExecutorService.Cancel.
func (c *executorServiceClient) Cancel(ctx context.Context, req *connect.Request[executorpb.CancelRequest]) (*connect.Response[executorpb.CancelResponse], error) {
	return c.cancel.CallUnary(ctx, req)
}

// JobOutput calls rafiki.executor.v1.ExecutorService.JobOutput.
func (c *executorServiceClient) JobOutput(ctx context.Context, req *connect.Request[executorpb.JobOutputRequest]) (*connect.Response[executorpb.JobOutputResponse], error) {
	return c.jobOutput.CallUnary(ctx, req)
}

// Provision calls rafiki.executor.v1.ExecutorService.Provision.
func (c *executorServiceClient) Provision(ctx context.Context, req *connect.Request[executorpb.ProvisionRequest]) (*connect.Response[executorpb.ProvisionResponse], error) {
	return c.provision.CallUnary(ctx, req)
}

// Release calls rafiki.executor.v1.ExecutorService.Release.
func (c *executorServiceClient) Release(ctx context.Context, req *connect.Request[executorpb.ReleaseRequest]) (*connect.Response[executorpb.ReleaseResponse], error) {
	return c.release.CallUnary(ctx, req)
}

// ProjectContext calls rafiki.executor.v1.ExecutorService.ProjectContext.
func (c *executorServiceClient) ProjectContext(ctx context.Context, req *connect.Request[executorpb.ProjectContextRequest]) (*connect.Response[executorpb.ProjectContextResponse], error) {
	return c.projectContext.CallUnary(ctx, req)
}

// ProjectSkills calls rafiki.executor.v1.ExecutorService.ProjectSkills.
func (c *executorServiceClient) ProjectSkills(ctx context.Context, req *connect.Request[executorpb.ProjectSkillsRequest]) (*connect.Response[executorpb.ProjectSkillsResponse], error) {
	return c.projectSkills.CallUnary(ctx, req)
}

// SkillBody calls rafiki.executor.v1.ExecutorService.SkillBody.
func (c *executorServiceClient) SkillBody(ctx context.Context, req *connect.Request[executorpb.SkillBodyRequest]) (*connect.Response[executorpb.SkillBodyResponse], error) {
	return c.skillBody.CallUnary(ctx, req)
}

// Proxy calls rafiki.executor.v1.ExecutorService.Proxy.
func (c *executorServiceClient) Proxy(ctx context.Context) *connect.BidiStreamForClient[executorpb.ProxyRequest, executorpb.ProxyResponse] {
	return c.proxy.CallBidiStream(ctx)
}

// ExecutorServiceHandler is an implementation of the rafiki.executor.v1.ExecutorService service.
type ExecutorServiceHandler interface {
	Describe(context.Context, *connect.Request[executorpb.DescribeRequest]) (*connect.Response[executorpb.DescribeResponse], error)
	Health(context.Context, *connect.Request[executorpb.HealthRequest]) (*connect.Response[executorpb.HealthResponse], error)
	Execute(context.Context, *connect.Request[executorpb.ExecuteRequest], *connect.ServerStream[executorpb.ExecuteResponse]) error
	Attach(context.Context, *connect.Request[executorpb.AttachRequest], *connect.ServerStream[executorpb.AttachResponse]) error
	Cancel(context.Context, *connect.Request[executorpb.CancelRequest]) (*connect.Response[executorpb.CancelResponse], error)
	JobOutput(context.Context, *connect.Request[executorpb.JobOutputRequest]) (*connect.Response[executorpb.JobOutputResponse], error)
	// Provision prepares a workspace for one child and returns a handle every
	// later Execute carries. A native executor answers with its pinned root and
	// does nothing else; a container executor starts a container.
	Provision(context.Context, *connect.Request[executorpb.ProvisionRequest]) (*connect.Response[executorpb.ProvisionResponse], error)
	// Release tears a workspace down. Idempotent: a daemon restart that lost
	// track of a workspace must be able to release it again without error.
	Release(context.Context, *connect.Request[executorpb.ReleaseRequest]) (*connect.Response[executorpb.ReleaseResponse], error)
	// ProjectContext returns the instruction files belonging to a workspace:
	// CLAUDE.md and AGENTS.md at the git root and at the workdir, with @includes
	// already expanded.
	//
	// It is a separate call rather than a field on ProvisionResponse because it
	// returns CONTENT, and content is unbounded where a workspace handle is not:
	// a large CLAUDE.md would make every provision pay for it. It is separate
	// from Describe for a different reason — Describe is per-EXECUTOR and this is
	// per-workspace, so Describe structurally cannot answer it.
	ProjectContext(context.Context, *connect.Request[executorpb.ProjectContextRequest]) (*connect.Response[executorpb.ProjectContextResponse], error)
	// ProjectSkills returns the skills discovered in a workspace — the project
	// tier only. User and system skills belong to whoever runs the agent loop and
	// are never reported here.
	//
	// Metadata only. Bodies are fetched by SkillBody on the turn a model actually
	// asks for one: an inventory is a handful of lines per skill, while a body is
	// a document, and returning every body at spawn would put the whole project's
	// skill text into every child.
	ProjectSkills(context.Context, *connect.Request[executorpb.ProjectSkillsRequest]) (*connect.Response[executorpb.ProjectSkillsResponse], error)
	// SkillBody returns one project skill's body, resolved by NAME against the
	// executor's own discovery.
	//
	// By name and not by path, for the same reason ProjectContext takes a
	// workspace id: a path parameter would let anything that reaches this
	// executor read an arbitrary file on it.
	SkillBody(context.Context, *connect.Request[executorpb.SkillBodyRequest]) (*connect.Response[executorpb.SkillBodyResponse], error)
	// Proxy relays one HTTP request to a pre-declared LLM endpoint and streams
	// the response back. One stream per request/response cycle.
	Proxy(context.Context, *connect.BidiStream[executorpb.ProxyRequest, executorpb.ProxyResponse]) error
}

// NewExecutorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecutorServiceHandler(svc ExecutorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	executorServiceMethods := executorpb.File_executor_proto.Services().ByName("ExecutorService").Methods()
	executorServiceDescribeHandler := connect.NewUnaryHandler(
		ExecutorServiceDescribeProcedure,
		svc.Describe,
		connect.WithSchema(executorServiceMethods.ByName("Describe")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceHealthHandler := connect.NewUnaryHandler(
		ExecutorServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(executorServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceExecuteHandler := connect.NewServerStreamHandler(
		ExecutorServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(executorServiceMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceAttachHandler := connect.NewServerStreamHandler(
		ExecutorServiceAttachProcedure,
		svc.Attach,
		connect.WithSchema(executorServiceMethods.ByName("Attach")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceCancelHandler := connect.NewUnaryHandler(
		ExecutorServiceCancelProcedure,
		svc.Cancel,
		connect.WithSchema(executorServiceMethods.ByName("Cancel")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceJobOutputHandler := connect.NewUnaryHandler(
		ExecutorServiceJobOutputProcedure,
		svc.JobOutput,
		connect.WithSchema(executorServiceMethods.ByName("JobOutput")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceProvisionHandler := connect.NewUnaryHandler(
		ExecutorServiceProvisionProcedure,
		svc.Provision,
		connect.WithSchema(executorServiceMethods.ByName("Provision")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceReleaseHandler := connect.NewUnaryHandler(
		ExecutorServiceReleaseProcedure,
		svc.Release,
		connect.WithSchema(executorServiceMethods.ByName("Release")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceProjectContextHandler := connect.NewUnaryHandler(
		ExecutorServiceProjectContextProcedure,
		svc.ProjectContext,
		connect.WithSchema(executorServiceMethods.ByName("ProjectContext")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceProjectSkillsHandler := connect.NewUnaryHandler(
		ExecutorServiceProjectSkillsProcedure,
		svc.ProjectSkills,
		connect.WithSchema(executorServiceMethods.ByName("ProjectSkills")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceSkillBodyHandler := connect.NewUnaryHandler(
		ExecutorServiceSkillBodyProcedure,
		svc.SkillBody,
		connect.WithSchema(executorServiceMethods.ByName("SkillBody")),
		connect.WithHandlerOptions(opts...),
	)
	executorServiceProxyHandler := connect.NewBidiStreamHandler(
		ExecutorServiceProxyProcedure,
		svc.Proxy,
		connect.WithSchema(executorServiceMethods.ByName("Proxy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rafiki.executor.v1.ExecutorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecutorServiceDescribeProcedure:
			executorServiceDescribeHandler.ServeHTTP(w, r)
		case ExecutorServiceHealthProcedure:
			executorServiceHealthHandler.ServeHTTP(w, r)
		case ExecutorServiceExecuteProcedure:
			executorServiceExecuteHandler.ServeHTTP(w, r)
		case ExecutorServiceAttachProcedure:
			executorServiceAttachHandler.ServeHTTP(w, r)
		case ExecutorServiceCancelProcedure:
			executorServiceCancelHandler.ServeHTTP(w, r)
		case ExecutorServiceJobOutputProcedure:
			executorServiceJobOutputHandler.ServeHTTP(w, r)
		case ExecutorServiceProvisionProcedure:
			executorServiceProvisionHandler.ServeHTTP(w, r)
		case ExecutorServiceReleaseProcedure:
			executorServiceReleaseHandler.ServeHTTP(w, r)
		case ExecutorServiceProjectContextProcedure:
			executorServiceProjectContextHandler.ServeHTTP(w, r)
		case ExecutorServiceProjectSkillsProcedure:
			executorServiceProjectSkillsHandler.ServeHTTP(w, r)
		case ExecutorServiceSkillBodyProcedure:
			executorServiceSkillBodyHandler.ServeHTTP(w, r)
		case ExecutorServiceProxyProcedure:
			executorServiceProxyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecutorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExecutorServiceHandler struct{}

func (UnimplementedExecutorServiceHandler) Describe(context.Context, *connect.Request[executorpb.DescribeRequest]) (*connect.Response[executorpb.DescribeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Describe is not implemented"))
}

func (UnimplementedExecutorServiceHandler) Health(context.Context, *connect.Request[executorpb.HealthRequest]) (*connect.Response[executorpb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Health is not implemented"))
}

func (UnimplementedExecutorServiceHandler) Execute(context.Context, *connect.Request[executorpb.ExecuteRequest], *connect.ServerStream[executorpb.ExecuteResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Execute is not implemented"))
}

func (UnimplementedExecutorServiceHandler) Attach(context.Context, *connect.Request[executorpb.AttachRequest], *connect.ServerStream[executorpb.AttachResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Attach is not implemented"))
}

func (UnimplementedExecutorServiceHandler) Cancel(context.Context, *connect.Request[executorpb.CancelRequest]) (*connect.Response[executorpb.CancelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Cancel is not implemented"))
}

func (UnimplementedExecutorServiceHandler) JobOutput(context.Context, *connect.Request[executorpb.JobOutputRequest]) (*connect.Response[executorpb.JobOutputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.JobOutput is not implemented"))
}

func (UnimplementedExecutorServiceHandler) Provision(context.Context, *connect.Request[executorpb.ProvisionRequest]) (*connect.Response[executorpb.ProvisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Provision is not implemented"))
}

func (UnimplementedExecutorServiceHandler) Release(context.Context, *connect.Request[executorpb.ReleaseRequest]) (*connect.Response[executorpb.ReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Release is not implemented"))
}

func (UnimplementedExecutorServiceHandler) ProjectContext(context.Context, *connect.Request[executorpb.ProjectContextRequest]) (*connect.Response[executorpb.ProjectContextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.ProjectContext is not implemented"))
}

func (UnimplementedExecutorServiceHandler) ProjectSkills(context.Context, *connect.Request[executorpb.ProjectSkillsRequest]) (*connect.Response[executorpb.ProjectSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.ProjectSkills is not implemented"))
}

func (UnimplementedExecutorServiceHandler) SkillBody(context.Context, *connect.Request[executorpb.SkillBodyRequest]) (*connect.Response[executorpb.SkillBodyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.SkillBody is not implemented"))
}

func (UnimplementedExecutorServiceHandler) Proxy(context.Context, *connect.BidiStream[executorpb.ProxyRequest, executorpb.ProxyResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.executor.v1.ExecutorService.Proxy is not implemented"))
}
