// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: executor.proto

package executorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Failure_Code int32

const (
	Failure_CODE_UNSPECIFIED   Failure_Code = 0
	Failure_CODE_DENIED        Failure_Code = 1
	Failure_CODE_EXECUTOR_LOST Failure_Code = 2
	Failure_CODE_TOOL_FAILED   Failure_Code = 3
	Failure_CODE_TIMEOUT       Failure_Code = 4
)

// Enum value maps for Failure_Code.
var (
	Failure_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_DENIED",
		2: "CODE_EXECUTOR_LOST",
		3: "CODE_TOOL_FAILED",
		4: "CODE_TIMEOUT",
	}
	Failure_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":   0,
		"CODE_DENIED":        1,
		"CODE_EXECUTOR_LOST": 2,
		"CODE_TOOL_FAILED":   3,
		"CODE_TIMEOUT":       4,
	}
)

func (x Failure_Code) Enum() *Failure_Code {
	p := new(Failure_Code)
	*p = x
	return p
}

func (x Failure_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_executor_proto_enumTypes[0].Descriptor()
}

func (Failure_Code) Type() protoreflect.EnumType {
	return &file_executor_proto_enumTypes[0]
}

func (x Failure_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure_Code.Descriptor instead.
func (Failure_Code) EnumDescriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10, 0}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId         string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	Platform           string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Roots              []string               `protobuf:"bytes,3,rep,name=roots,proto3" json:"roots,omitempty"`
	Concurrency        int32                  `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Isolation          string                 `protobuf:"bytes,5,opt,name=isolation,proto3" json:"isolation,omitempty"`
	WorkspaceMode      string                 `protobuf:"bytes,6,opt,name=workspace_mode,json=workspaceMode,proto3" json:"workspace_mode,omitempty"`
	Tools              []string               `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	Version            string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	SelfReportedLabels map[string]string      `protobuf:"bytes,9,rep,name=self_reported_labels,json=selfReportedLabels,proto3" json:"self_reported_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *DescribeResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DescribeResponse) GetRoots() []string {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *DescribeResponse) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *DescribeResponse) GetIsolation() string {
	if x != nil {
		return x.Isolation
	}
	return ""
}

func (x *DescribeResponse) GetWorkspaceMode() string {
	if x != nil {
		return x.WorkspaceMode
	}
	return ""
}

func (x *DescribeResponse) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetSelfReportedLabels() map[string]string {
	if x != nil {
		return x.SelfReportedLabels
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Load           float64                `protobuf:"fixed64,1,opt,name=load,proto3" json:"load,omitempty"`
	RunningHandles []string               `protobuf:"bytes,2,rep,name=running_handles,json=runningHandles,proto3" json:"running_handles,omitempty"`
	DiskFreeBytes  int64                  `protobuf:"varint,3,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	Draining       bool                   `protobuf:"varint,4,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *HealthResponse) GetRunningHandles() []string {
	if x != nil {
		return x.RunningHandles
	}
	return nil
}

func (x *HealthResponse) GetDiskFreeBytes() int64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *HealthResponse) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Block:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_Image
	Block         isContentBlock_Block `protobuf_oneof:"block"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *ContentBlock) GetBlock() isContentBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ContentBlock) GetText() string {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ContentBlock) GetImage() *ImageBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isContentBlock_Block interface {
	isContentBlock_Block()
}

type ContentBlock_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_Image struct {
	Image *ImageBlock `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_Block() {}

func (*ContentBlock_Image) isContentBlock_Block() {}

type ImageBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBlock) Reset() {
	*x = ImageBlock{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBlock) ProtoMessage() {}

func (x *ImageBlock) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBlock.ProtoReflect.Descriptor instead.
func (*ImageBlock) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *ImageBlock) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ImageBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	InputJson     []byte                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	ExpectMtime   map[string]int64       `protobuf:"bytes,5,rep,name=expect_mtime,json=expectMtime,proto3" json:"expect_mtime,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Background    bool                   `protobuf:"varint,6,opt,name=background,proto3" json:"background,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ExecuteRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ExecuteRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteRequest) GetExpectMtime() map[string]int64 {
	if x != nil {
		return x.ExpectMtime
	}
	return nil
}

func (x *ExecuteRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteResponse_Output
	//	*ExecuteResponse_Result
	//	*ExecuteResponse_Failed
	//	*ExecuteResponse_Handle
	Event         isExecuteResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetEvent() isExecuteResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteResponse) GetOutput() *OutputChunk {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ExecuteResponse) GetResult() *Result {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecuteResponse) GetFailed() *Failure {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *ExecuteResponse) GetHandle() string {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Handle); ok {
			return x.Handle
		}
	}
	return ""
}

type isExecuteResponse_Event interface {
	isExecuteResponse_Event()
}

type ExecuteResponse_Output struct {
	Output *OutputChunk `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ExecuteResponse_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ExecuteResponse_Failed struct {
	Failed *Failure `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

type ExecuteResponse_Handle struct {
	Handle string `protobuf:"bytes,4,opt,name=handle,proto3,oneof"`
}

func (*ExecuteResponse_Output) isExecuteResponse_Event() {}

func (*ExecuteResponse_Result) isExecuteResponse_Event() {}

func (*ExecuteResponse_Failed) isExecuteResponse_Event() {}

func (*ExecuteResponse_Handle) isExecuteResponse_Event() {}

type OutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{8}
}

func (x *OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*ContentBlock        `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ObservedMtime map[string]int64       `protobuf:"bytes,3,rep,name=observed_mtime,json=observedMtime,proto3" json:"observed_mtime,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{9}
}

func (x *Result) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Result) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *Result) GetObservedMtime() map[string]int64 {
	if x != nil {
		return x.ObservedMtime
	}
	return nil
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Failure_Code           `protobuf:"varint,1,opt,name=code,proto3,enum=rafiki.executor.v1.Failure_Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10}
}

func (x *Failure) GetCode() Failure_Code {
	if x != nil {
		return x.Code
	}
	return Failure_CODE_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{11}
}

func (x *AttachRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type AttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AttachResponse_Output
	//	*AttachResponse_ExitCode
	Event         isAttachResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{12}
}

func (x *AttachResponse) GetEvent() isAttachResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AttachResponse) GetOutput() *OutputChunk {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *AttachResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isAttachResponse_Event interface {
	isAttachResponse_Event()
}

type AttachResponse_Output struct {
	Output *OutputChunk `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type AttachResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*AttachResponse_Output) isAttachResponse_Event() {}

func (*AttachResponse_ExitCode) isAttachResponse_Event() {}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{13}
}

func (x *CancelRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{14}
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\x12rafiki.executor.v1\"\x11\n" +
	"\x0fDescribeRequest\"\xb3\x03\n" +
	"\x10DescribeResponse\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05roots\x18\x03 \x03(\tR\x05roots\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\x12\x1c\n" +
	"\tisolation\x18\x05 \x01(\tR\tisolation\x12%\n" +
	"\x0eworkspace_mode\x18\x06 \x01(\tR\rworkspaceMode\x12\x14\n" +
	"\x05tools\x18\a \x03(\tR\x05tools\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12n\n" +
	"\x14self_reported_labels\x18\t \x03(\v2<.rafiki.executor.v1.DescribeResponse.SelfReportedLabelsEntryR\x12selfReportedLabels\x1aE\n" +
	"\x17SelfReportedLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\x91\x01\n" +
	"\x0eHealthResponse\x12\x12\n" +
	"\x04load\x18\x01 \x01(\x01R\x04load\x12'\n" +
	"\x0frunning_handles\x18\x02 \x03(\tR\x0erunningHandles\x12&\n" +
	"\x0fdisk_free_bytes\x18\x03 \x01(\x03R\rdiskFreeBytes\x12\x1a\n" +
	"\bdraining\x18\x04 \x01(\bR\bdraining\"e\n" +
	"\fContentBlock\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x126\n" +
	"\x05image\x18\x02 \x01(\v2\x1e.rafiki.executor.v1.ImageBlockH\x00R\x05imageB\a\n" +
	"\x05block\"?\n" +
	"\n" +
	"ImageBlock\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xb3\x02\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\fR\tinputJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12V\n" +
	"\fexpect_mtime\x18\x05 \x03(\v23.rafiki.executor.v1.ExecuteRequest.ExpectMtimeEntryR\vexpectMtime\x12\x1e\n" +
	"\n" +
	"background\x18\x06 \x01(\bR\n" +
	"background\x1a>\n" +
	"\x10ExpectMtimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xdc\x01\n" +
	"\x0fExecuteResponse\x129\n" +
	"\x06output\x18\x01 \x01(\v2\x1f.rafiki.executor.v1.OutputChunkH\x00R\x06output\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1a.rafiki.executor.v1.ResultH\x00R\x06result\x125\n" +
	"\x06failed\x18\x03 \x01(\v2\x1b.rafiki.executor.v1.FailureH\x00R\x06failed\x12\x18\n" +
	"\x06handle\x18\x04 \x01(\tH\x00R\x06handleB\a\n" +
	"\x05event\"!\n" +
	"\vOutputChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xf7\x01\n" +
	"\x06Result\x12:\n" +
	"\acontent\x18\x01 \x03(\v2 .rafiki.executor.v1.ContentBlockR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12T\n" +
	"\x0eobserved_mtime\x18\x03 \x03(\v2-.rafiki.executor.v1.Result.ObservedMtimeEntryR\robservedMtime\x1a@\n" +
	"\x12ObservedMtimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc8\x01\n" +
	"\aFailure\x124\n" +
	"\x04code\x18\x01 \x01(\x0e2 .rafiki.executor.v1.Failure.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"m\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCODE_DENIED\x10\x01\x12\x16\n" +
	"\x12CODE_EXECUTOR_LOST\x10\x02\x12\x14\n" +
	"\x10CODE_TOOL_FAILED\x10\x03\x12\x10\n" +
	"\fCODE_TIMEOUT\x10\x04\"'\n" +
	"\rAttachRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"s\n" +
	"\x0eAttachResponse\x129\n" +
	"\x06output\x18\x01 \x01(\v2\x1f.rafiki.executor.v1.OutputChunkH\x00R\x06output\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCodeB\a\n" +
	"\x05event\"(\n" +
	"\rCancelRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"\x10\n" +
	"\x0eCancelResponse2\xb3\x03\n" +
	"\x0fExecutorService\x12U\n" +
	"\bDescribe\x12#.rafiki.executor.v1.DescribeRequest\x1a$.rafiki.executor.v1.DescribeResponse\x12O\n" +
	"\x06Health\x12!.rafiki.executor.v1.HealthRequest\x1a\".rafiki.executor.v1.HealthResponse\x12T\n" +
	"\aExecute\x12\".rafiki.executor.v1.ExecuteRequest\x1a#.rafiki.executor.v1.ExecuteResponse0\x01\x12Q\n" +
	"\x06Attach\x12!.rafiki.executor.v1.AttachRequest\x1a\".rafiki.executor.v1.AttachResponse0\x01\x12O\n" +
	"\x06Cancel\x12!.rafiki.executor.v1.CancelRequest\x1a\".rafiki.executor.v1.CancelResponseB3Z1go.graveland.dev/rafiki/pkg/executorpb;executorpbb\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_executor_proto_goTypes = []any{
	(Failure_Code)(0),        // 0: rafiki.executor.v1.Failure.Code
	(*DescribeRequest)(nil),  // 1: rafiki.executor.v1.DescribeRequest
	(*DescribeResponse)(nil), // 2: rafiki.executor.v1.DescribeResponse
	(*HealthRequest)(nil),    // 3: rafiki.executor.v1.HealthRequest
	(*HealthResponse)(nil),   // 4: rafiki.executor.v1.HealthResponse
	(*ContentBlock)(nil),     // 5: rafiki.executor.v1.ContentBlock
	(*ImageBlock)(nil),       // 6: rafiki.executor.v1.ImageBlock
	(*ExecuteRequest)(nil),   // 7: rafiki.executor.v1.ExecuteRequest
	(*ExecuteResponse)(nil),  // 8: rafiki.executor.v1.ExecuteResponse
	(*OutputChunk)(nil),      // 9: rafiki.executor.v1.OutputChunk
	(*Result)(nil),           // 10: rafiki.executor.v1.Result
	(*Failure)(nil),          // 11: rafiki.executor.v1.Failure
	(*AttachRequest)(nil),    // 12: rafiki.executor.v1.AttachRequest
	(*AttachResponse)(nil),   // 13: rafiki.executor.v1.AttachResponse
	(*CancelRequest)(nil),    // 14: rafiki.executor.v1.CancelRequest
	(*CancelResponse)(nil),   // 15: rafiki.executor.v1.CancelResponse
	nil,                      // 16: rafiki.executor.v1.DescribeResponse.SelfReportedLabelsEntry
	nil,                      // 17: rafiki.executor.v1.ExecuteRequest.ExpectMtimeEntry
	nil,                      // 18: rafiki.executor.v1.Result.ObservedMtimeEntry
}
var file_executor_proto_depIdxs = []int32{
	16, // 0: rafiki.executor.v1.DescribeResponse.self_reported_labels:type_name -> rafiki.executor.v1.DescribeResponse.SelfReportedLabelsEntry
	6,  // 1: rafiki.executor.v1.ContentBlock.image:type_name -> rafiki.executor.v1.ImageBlock
	17, // 2: rafiki.executor.v1.ExecuteRequest.expect_mtime:type_name -> rafiki.executor.v1.ExecuteRequest.ExpectMtimeEntry
	9,  // 3: rafiki.executor.v1.ExecuteResponse.output:type_name -> rafiki.executor.v1.OutputChunk
	10, // 4: rafiki.executor.v1.ExecuteResponse.result:type_name -> rafiki.executor.v1.Result
	11, // 5: rafiki.executor.v1.ExecuteResponse.failed:type_name -> rafiki.executor.v1.Failure
	5,  // 6: rafiki.executor.v1.Result.content:type_name -> rafiki.executor.v1.ContentBlock
	18, // 7: rafiki.executor.v1.Result.observed_mtime:type_name -> rafiki.executor.v1.Result.ObservedMtimeEntry
	0,  // 8: rafiki.executor.v1.Failure.code:type_name -> rafiki.executor.v1.Failure.Code
	9,  // 9: rafiki.executor.v1.AttachResponse.output:type_name -> rafiki.executor.v1.OutputChunk
	1,  // 10: rafiki.executor.v1.ExecutorService.Describe:input_type -> rafiki.executor.v1.DescribeRequest
	3,  // 11: rafiki.executor.v1.ExecutorService.Health:input_type -> rafiki.executor.v1.HealthRequest
	7,  // 12: rafiki.executor.v1.ExecutorService.Execute:input_type -> rafiki.executor.v1.ExecuteRequest
	12, // 13: rafiki.executor.v1.ExecutorService.Attach:input_type -> rafiki.executor.v1.AttachRequest
	14, // 14: rafiki.executor.v1.ExecutorService.Cancel:input_type -> rafiki.executor.v1.CancelRequest
	2,  // 15: rafiki.executor.v1.ExecutorService.Describe:output_type -> rafiki.executor.v1.DescribeResponse
	4,  // 16: rafiki.executor.v1.ExecutorService.Health:output_type -> rafiki.executor.v1.HealthResponse
	8,  // 17: rafiki.executor.v1.ExecutorService.Execute:output_type -> rafiki.executor.v1.ExecuteResponse
	13, // 18: rafiki.executor.v1.ExecutorService.Attach:output_type -> rafiki.executor.v1.AttachResponse
	15, // 19: rafiki.executor.v1.ExecutorService.Cancel:output_type -> rafiki.executor.v1.CancelResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	file_executor_proto_msgTypes[4].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_Image)(nil),
	}
	file_executor_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecuteResponse_Output)(nil),
		(*ExecuteResponse_Result)(nil),
		(*ExecuteResponse_Failed)(nil),
		(*ExecuteResponse_Handle)(nil),
	}
	file_executor_proto_msgTypes[12].OneofWrappers = []any{
		(*AttachResponse_Output)(nil),
		(*AttachResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		EnumInfos:         file_executor_proto_enumTypes,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
