// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: executor.proto

package executorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Failure_Code int32

const (
	Failure_CODE_UNSPECIFIED   Failure_Code = 0
	Failure_CODE_DENIED        Failure_Code = 1
	Failure_CODE_EXECUTOR_LOST Failure_Code = 2
	Failure_CODE_TOOL_FAILED   Failure_Code = 3
	Failure_CODE_TIMEOUT       Failure_Code = 4
)

// Enum value maps for Failure_Code.
var (
	Failure_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_DENIED",
		2: "CODE_EXECUTOR_LOST",
		3: "CODE_TOOL_FAILED",
		4: "CODE_TIMEOUT",
	}
	Failure_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":   0,
		"CODE_DENIED":        1,
		"CODE_EXECUTOR_LOST": 2,
		"CODE_TOOL_FAILED":   3,
		"CODE_TIMEOUT":       4,
	}
)

func (x Failure_Code) Enum() *Failure_Code {
	p := new(Failure_Code)
	*p = x
	return p
}

func (x Failure_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_executor_proto_enumTypes[0].Descriptor()
}

func (Failure_Code) Type() protoreflect.EnumType {
	return &file_executor_proto_enumTypes[0]
}

func (x Failure_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure_Code.Descriptor instead.
func (Failure_Code) EnumDescriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10, 0}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutorId         string                 `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	Platform           string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Roots              []string               `protobuf:"bytes,3,rep,name=roots,proto3" json:"roots,omitempty"`
	Concurrency        int32                  `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Isolation          string                 `protobuf:"bytes,5,opt,name=isolation,proto3" json:"isolation,omitempty"`
	WorkspaceMode      string                 `protobuf:"bytes,6,opt,name=workspace_mode,json=workspaceMode,proto3" json:"workspace_mode,omitempty"`
	Tools              []string               `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	Version            string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	SelfReportedLabels map[string]string      `protobuf:"bytes,9,rep,name=self_reported_labels,json=selfReportedLabels,proto3" json:"self_reported_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// proxies are the LLM-endpoint names this executor will forward to, declared
	// by its operator with --proxy at startup. Unlike isolation and
	// workspace_mode, this is safe to self-report: it only ever NARROWS what the
	// executor will do, it is enforced on this side rather than trusted on the
	// daemon's, and a missing or wrong entry costs a failed request rather than
	// opening a machine.
	Proxies []string `protobuf:"bytes,10,rep,name=proxies,proto3" json:"proxies,omitempty"`
	// launch_kinds are the child protocols this executor will host via
	// AdminService.Launch, declared by its operator with --launch at startup.
	// Safe to self-report for the same reason as proxies: it only ever NARROWS
	// what this executor will do. The daemon still requires the child's ordinary
	// executor selector to match, so a wrong entry costs a failed launch rather
	// than admitting anyone.
	LaunchKinds   []string `protobuf:"bytes,11,rep,name=launch_kinds,json=launchKinds,proto3" json:"launch_kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *DescribeResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DescribeResponse) GetRoots() []string {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *DescribeResponse) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *DescribeResponse) GetIsolation() string {
	if x != nil {
		return x.Isolation
	}
	return ""
}

func (x *DescribeResponse) GetWorkspaceMode() string {
	if x != nil {
		return x.WorkspaceMode
	}
	return ""
}

func (x *DescribeResponse) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetSelfReportedLabels() map[string]string {
	if x != nil {
		return x.SelfReportedLabels
	}
	return nil
}

func (x *DescribeResponse) GetProxies() []string {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *DescribeResponse) GetLaunchKinds() []string {
	if x != nil {
		return x.LaunchKinds
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Load           float64                `protobuf:"fixed64,1,opt,name=load,proto3" json:"load,omitempty"`
	RunningHandles []string               `protobuf:"bytes,2,rep,name=running_handles,json=runningHandles,proto3" json:"running_handles,omitempty"`
	DiskFreeBytes  int64                  `protobuf:"varint,3,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	Draining       bool                   `protobuf:"varint,4,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *HealthResponse) GetRunningHandles() []string {
	if x != nil {
		return x.RunningHandles
	}
	return nil
}

func (x *HealthResponse) GetDiskFreeBytes() int64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *HealthResponse) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Block:
	//
	//	*ContentBlock_Text
	//	*ContentBlock_Image
	Block         isContentBlock_Block `protobuf_oneof:"block"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *ContentBlock) GetBlock() isContentBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ContentBlock) GetText() string {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ContentBlock) GetImage() *ImageBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isContentBlock_Block interface {
	isContentBlock_Block()
}

type ContentBlock_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentBlock_Image struct {
	Image *ImageBlock `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_Block() {}

func (*ContentBlock_Image) isContentBlock_Block() {}

type ImageBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBlock) Reset() {
	*x = ImageBlock{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBlock) ProtoMessage() {}

func (x *ImageBlock) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBlock.ProtoReflect.Descriptor instead.
func (*ImageBlock) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *ImageBlock) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ImageBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecuteRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CallId      string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Tool        string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	InputJson   []byte                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	TimeoutMs   int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	ExpectMtime map[string]int64       `protobuf:"bytes,5,rep,name=expect_mtime,json=expectMtime,proto3" json:"expect_mtime,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Background  bool                   `protobuf:"varint,6,opt,name=background,proto3" json:"background,omitempty"`
	// workspace_id selects the workspace this call runs in. Empty means the
	// executor's own root — the pre-phase-08 behaviour, kept so an executor and
	// a daemon of different vintages still interoperate.
	WorkspaceId   string `protobuf:"bytes,7,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ExecuteRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ExecuteRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteRequest) GetExpectMtime() map[string]int64 {
	if x != nil {
		return x.ExpectMtime
	}
	return nil
}

func (x *ExecuteRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

func (x *ExecuteRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteResponse_Output
	//	*ExecuteResponse_Result
	//	*ExecuteResponse_Failed
	//	*ExecuteResponse_Handle
	Event         isExecuteResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetEvent() isExecuteResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteResponse) GetOutput() *OutputChunk {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ExecuteResponse) GetResult() *Result {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecuteResponse) GetFailed() *Failure {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *ExecuteResponse) GetHandle() string {
	if x != nil {
		if x, ok := x.Event.(*ExecuteResponse_Handle); ok {
			return x.Handle
		}
	}
	return ""
}

type isExecuteResponse_Event interface {
	isExecuteResponse_Event()
}

type ExecuteResponse_Output struct {
	Output *OutputChunk `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ExecuteResponse_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ExecuteResponse_Failed struct {
	Failed *Failure `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

type ExecuteResponse_Handle struct {
	Handle string `protobuf:"bytes,4,opt,name=handle,proto3,oneof"`
}

func (*ExecuteResponse_Output) isExecuteResponse_Event() {}

func (*ExecuteResponse_Result) isExecuteResponse_Event() {}

func (*ExecuteResponse_Failed) isExecuteResponse_Event() {}

func (*ExecuteResponse_Handle) isExecuteResponse_Event() {}

type OutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{8}
}

func (x *OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*ContentBlock        `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ObservedMtime map[string]int64       `protobuf:"bytes,3,rep,name=observed_mtime,json=observedMtime,proto3" json:"observed_mtime,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{9}
}

func (x *Result) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Result) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *Result) GetObservedMtime() map[string]int64 {
	if x != nil {
		return x.ObservedMtime
	}
	return nil
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Failure_Code           `protobuf:"varint,1,opt,name=code,proto3,enum=rafiki.executor.v1.Failure_Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10}
}

func (x *Failure) GetCode() Failure_Code {
	if x != nil {
		return x.Code
	}
	return Failure_CODE_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{11}
}

func (x *AttachRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type AttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AttachResponse_Output
	//	*AttachResponse_ExitCode
	Event         isAttachResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{12}
}

func (x *AttachResponse) GetEvent() isAttachResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AttachResponse) GetOutput() *OutputChunk {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *AttachResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isAttachResponse_Event interface {
	isAttachResponse_Event()
}

type AttachResponse_Output struct {
	Output *OutputChunk `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type AttachResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*AttachResponse_Output) isAttachResponse_Event() {}

func (*AttachResponse_ExitCode) isAttachResponse_Event() {}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{13}
}

func (x *CancelRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{14}
}

// Mount is one bind mount. The DAEMON derives these from the child's worktree
// assignment; the model never writes a path, and the executor never invents
// one. Anything the executor added here would be a grant nobody authorised.
type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPath      string                 `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	ContainerPath string                 `protobuf:"bytes,2,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_executor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{15}
}

func (x *Mount) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *Mount) GetContainerPath() string {
	if x != nil {
		return x.ContainerPath
	}
	return ""
}

func (x *Mount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type ProvisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// child_id is the daemon's id for the child this workspace serves. It is
	// used for naming and for idempotency, never for authority.
	ChildId string `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	// ephemeral: the executor constructs the workspace and it is
	// reconstructible, so the child may be rescheduled elsewhere on loss.
	// pinned: the executor exposes an existing tree; losing it means park or
	// fail. This single field is what the park-vs-fail decision consults.
	WorkspaceMode string   `protobuf:"bytes,2,opt,name=workspace_mode,json=workspaceMode,proto3" json:"workspace_mode,omitempty"`
	Mounts        []*Mount `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// workdir is the container path the child's tools start in. It must be one
	// of the mounts' container_path values; an executor MUST reject anything
	// else rather than silently starting somewhere the child cannot write.
	Workdir string `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	// network is "none" or "bridge". Default none: an unattended worker that
	// does not need egress should not have it, and a build that needs a package
	// registry is a deliberate choice rather than an accident.
	Network string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// Resource caps. Zero means the executor's own default.
	MemoryBytes   int64             `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Cpus          float64           `protobuf:"fixed64,7,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Env           map[string]string `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_executor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{16}
}

func (x *ProvisionRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *ProvisionRequest) GetWorkspaceMode() string {
	if x != nil {
		return x.WorkspaceMode
	}
	return ""
}

func (x *ProvisionRequest) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ProvisionRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ProvisionRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ProvisionRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProvisionRequest) GetCpus() float64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *ProvisionRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ProvisionResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// roots the workspace actually exposes, as the CHILD will see them. The
	// daemon puts these in the child's system prompt (phase 09): a sandboxed
	// worker that does not know it is sandboxed misreads its first denial as a
	// broken repository.
	Roots         []string `protobuf:"bytes,2,rep,name=roots,proto3" json:"roots,omitempty"`
	Workdir       string   `protobuf:"bytes,3,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Isolation     string   `protobuf:"bytes,4,opt,name=isolation,proto3" json:"isolation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_executor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{17}
}

func (x *ProvisionResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ProvisionResponse) GetRoots() []string {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *ProvisionResponse) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ProvisionResponse) GetIsolation() string {
	if x != nil {
		return x.Isolation
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_executor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{18}
}

func (x *ReleaseRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_executor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{19}
}

type ProjectContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// workspace_id from Provision. The executor resolves the workdir itself
	// rather than taking a path, so a caller cannot ask for the contents of an
	// arbitrary directory on the executor's filesystem.
	WorkspaceId   string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectContextRequest) Reset() {
	*x = ProjectContextRequest{}
	mi := &file_executor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectContextRequest) ProtoMessage() {}

func (x *ProjectContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectContextRequest.ProtoReflect.Descriptor instead.
func (*ProjectContextRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{20}
}

func (x *ProjectContextRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ProjectContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Concatenated instruction-file content, includes already expanded. Empty is
	// the ordinary answer for a directory with neither file, and is not an error.
	//
	// Expanded on THIS side deliberately: an @include names a path on the
	// executor's filesystem, which the daemon cannot resolve.
	ContextFiles  string `protobuf:"bytes,1,opt,name=context_files,json=contextFiles,proto3" json:"context_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectContextResponse) Reset() {
	*x = ProjectContextResponse{}
	mi := &file_executor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectContextResponse) ProtoMessage() {}

func (x *ProjectContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectContextResponse.ProtoReflect.Descriptor instead.
func (*ProjectContextResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{21}
}

func (x *ProjectContextResponse) GetContextFiles() string {
	if x != nil {
		return x.ContextFiles
	}
	return ""
}

type ProjectSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSkillsRequest) Reset() {
	*x = ProjectSkillsRequest{}
	mi := &file_executor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSkillsRequest) ProtoMessage() {}

func (x *ProjectSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSkillsRequest.ProtoReflect.Descriptor instead.
func (*ProjectSkillsRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{22}
}

func (x *ProjectSkillsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ProjectSkill struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// dir is the skill's own directory as the EXECUTOR sees it. The daemon does
	// not resolve it — it is passed to the model as "Base directory for this
	// skill", which is correct precisely because the model's file tools run on
	// the executor too.
	Dir           string `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSkill) Reset() {
	*x = ProjectSkill{}
	mi := &file_executor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSkill) ProtoMessage() {}

func (x *ProjectSkill) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSkill.ProtoReflect.Descriptor instead.
func (*ProjectSkill) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{23}
}

func (x *ProjectSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectSkill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectSkill) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ProjectSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*ProjectSkill        `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSkillsResponse) Reset() {
	*x = ProjectSkillsResponse{}
	mi := &file_executor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSkillsResponse) ProtoMessage() {}

func (x *ProjectSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSkillsResponse.ProtoReflect.Descriptor instead.
func (*ProjectSkillsResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{24}
}

func (x *ProjectSkillsResponse) GetSkills() []*ProjectSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type SkillBodyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillBodyRequest) Reset() {
	*x = SkillBodyRequest{}
	mi := &file_executor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillBodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillBodyRequest) ProtoMessage() {}

func (x *SkillBodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillBodyRequest.ProtoReflect.Descriptor instead.
func (*SkillBodyRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{25}
}

func (x *SkillBodyRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SkillBodyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SkillBodyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Dir           string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillBodyResponse) Reset() {
	*x = SkillBodyResponse{}
	mi := &file_executor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillBodyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillBodyResponse) ProtoMessage() {}

func (x *SkillBodyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillBodyResponse.ProtoReflect.Descriptor instead.
func (*SkillBodyResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{26}
}

func (x *SkillBodyResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SkillBodyResponse) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

// JobOutput is the one-shot poll behind bash_output. Attach is a stream and
// draining it to answer "what has this printed so far" means either blocking
// until exit or racing a deadline.
type JobOutputRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// Byte offset into the job's lifetime output. 0 means "from whatever is
	// still retained". Pass back the previous response's `total` to poll.
	Since         int64 `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobOutputRequest) Reset() {
	*x = JobOutputRequest{}
	mi := &file_executor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOutputRequest) ProtoMessage() {}

func (x *JobOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOutputRequest.ProtoReflect.Descriptor instead.
func (*JobOutputRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{27}
}

func (x *JobOutputRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *JobOutputRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type JobOutputResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Bytes the job has ever written, including any dropped from the ring.
	Total    int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Exited   bool  `protobuf:"varint,3,opt,name=exited,proto3" json:"exited,omitempty"`
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// false when the handle is unknown — either never started, or reaped
	// after the retention window.
	Found         bool `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobOutputResponse) Reset() {
	*x = JobOutputResponse{}
	mi := &file_executor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOutputResponse) ProtoMessage() {}

func (x *JobOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOutputResponse.ProtoReflect.Descriptor instead.
func (*JobOutputResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{28}
}

func (x *JobOutputResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *JobOutputResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *JobOutputResponse) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *JobOutputResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobOutputResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ProxyStart opens one relayed HTTP request. The request is STRUCTURED rather
// than raw HTTP bytes: the executor rebuilds it against the base URL it already
// holds, so the target is constructed rather than parsed out of a byte stream
// and then validated. That removes HTTP parsing — request smuggling,
// absolute-form request lines, Host handling, pipelining — from in front of the
// one check that matters.
type ProxyStart struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProxyName string                 `protobuf:"bytes,1,opt,name=proxy_name,json=proxyName,proto3" json:"proxy_name,omitempty"`
	Method    string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// path is path+query only, joined onto the declared base. It must be rooted
	// and must not escape the base after cleaning.
	Path          string            `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyStart) Reset() {
	*x = ProxyStart{}
	mi := &file_executor_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStart) ProtoMessage() {}

func (x *ProxyStart) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStart.ProtoReflect.Descriptor instead.
func (*ProxyStart) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{29}
}

func (x *ProxyStart) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *ProxyStart) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyStart) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ProxyRequest_Start
	//	*ProxyRequest_Body
	Msg           isProxyRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_executor_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{30}
}

func (x *ProxyRequest) GetMsg() isProxyRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ProxyRequest) GetStart() *ProxyStart {
	if x != nil {
		if x, ok := x.Msg.(*ProxyRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ProxyRequest) GetBody() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ProxyRequest_Body); ok {
			return x.Body
		}
	}
	return nil
}

type isProxyRequest_Msg interface {
	isProxyRequest_Msg()
}

type ProxyRequest_Start struct {
	Start *ProxyStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // exactly once, first
}

type ProxyRequest_Body struct {
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3,oneof"` // request body chunks; half-close ends the body
}

func (*ProxyRequest_Start) isProxyRequest_Msg() {}

func (*ProxyRequest_Body) isProxyRequest_Msg() {}

type ProxyHead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyHead) Reset() {
	*x = ProxyHead{}
	mi := &file_executor_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHead) ProtoMessage() {}

func (x *ProxyHead) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHead.ProtoReflect.Descriptor instead.
func (*ProxyHead) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{31}
}

func (x *ProxyHead) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProxyHead) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ProxyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ProxyResponse_Head
	//	*ProxyResponse_Body
	Msg           isProxyResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_executor_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{32}
}

func (x *ProxyResponse) GetMsg() isProxyResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ProxyResponse) GetHead() *ProxyHead {
	if x != nil {
		if x, ok := x.Msg.(*ProxyResponse_Head); ok {
			return x.Head
		}
	}
	return nil
}

func (x *ProxyResponse) GetBody() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ProxyResponse_Body); ok {
			return x.Body
		}
	}
	return nil
}

type isProxyResponse_Msg interface {
	isProxyResponse_Msg()
}

type ProxyResponse_Head struct {
	Head *ProxyHead `protobuf:"bytes,1,opt,name=head,proto3,oneof"` // exactly once, first
}

type ProxyResponse_Body struct {
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3,oneof"` // response body chunks, flushed as they arrive
}

func (*ProxyResponse_Head) isProxyResponse_Msg() {}

func (*ProxyResponse_Body) isProxyResponse_Msg() {}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\x12rafiki.executor.v1\"\x11\n" +
	"\x0fDescribeRequest\"\xf0\x03\n" +
	"\x10DescribeResponse\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05roots\x18\x03 \x03(\tR\x05roots\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\x12\x1c\n" +
	"\tisolation\x18\x05 \x01(\tR\tisolation\x12%\n" +
	"\x0eworkspace_mode\x18\x06 \x01(\tR\rworkspaceMode\x12\x14\n" +
	"\x05tools\x18\a \x03(\tR\x05tools\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12n\n" +
	"\x14self_reported_labels\x18\t \x03(\v2<.rafiki.executor.v1.DescribeResponse.SelfReportedLabelsEntryR\x12selfReportedLabels\x12\x18\n" +
	"\aproxies\x18\n" +
	" \x03(\tR\aproxies\x12!\n" +
	"\flaunch_kinds\x18\v \x03(\tR\vlaunchKinds\x1aE\n" +
	"\x17SelfReportedLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\x91\x01\n" +
	"\x0eHealthResponse\x12\x12\n" +
	"\x04load\x18\x01 \x01(\x01R\x04load\x12'\n" +
	"\x0frunning_handles\x18\x02 \x03(\tR\x0erunningHandles\x12&\n" +
	"\x0fdisk_free_bytes\x18\x03 \x01(\x03R\rdiskFreeBytes\x12\x1a\n" +
	"\bdraining\x18\x04 \x01(\bR\bdraining\"e\n" +
	"\fContentBlock\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x126\n" +
	"\x05image\x18\x02 \x01(\v2\x1e.rafiki.executor.v1.ImageBlockH\x00R\x05imageB\a\n" +
	"\x05block\"?\n" +
	"\n" +
	"ImageBlock\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xd6\x02\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\fR\tinputJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12V\n" +
	"\fexpect_mtime\x18\x05 \x03(\v23.rafiki.executor.v1.ExecuteRequest.ExpectMtimeEntryR\vexpectMtime\x12\x1e\n" +
	"\n" +
	"background\x18\x06 \x01(\bR\n" +
	"background\x12!\n" +
	"\fworkspace_id\x18\a \x01(\tR\vworkspaceId\x1a>\n" +
	"\x10ExpectMtimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xdc\x01\n" +
	"\x0fExecuteResponse\x129\n" +
	"\x06output\x18\x01 \x01(\v2\x1f.rafiki.executor.v1.OutputChunkH\x00R\x06output\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1a.rafiki.executor.v1.ResultH\x00R\x06result\x125\n" +
	"\x06failed\x18\x03 \x01(\v2\x1b.rafiki.executor.v1.FailureH\x00R\x06failed\x12\x18\n" +
	"\x06handle\x18\x04 \x01(\tH\x00R\x06handleB\a\n" +
	"\x05event\"!\n" +
	"\vOutputChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xf7\x01\n" +
	"\x06Result\x12:\n" +
	"\acontent\x18\x01 \x03(\v2 .rafiki.executor.v1.ContentBlockR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12T\n" +
	"\x0eobserved_mtime\x18\x03 \x03(\v2-.rafiki.executor.v1.Result.ObservedMtimeEntryR\robservedMtime\x1a@\n" +
	"\x12ObservedMtimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc8\x01\n" +
	"\aFailure\x124\n" +
	"\x04code\x18\x01 \x01(\x0e2 .rafiki.executor.v1.Failure.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"m\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCODE_DENIED\x10\x01\x12\x16\n" +
	"\x12CODE_EXECUTOR_LOST\x10\x02\x12\x14\n" +
	"\x10CODE_TOOL_FAILED\x10\x03\x12\x10\n" +
	"\fCODE_TIMEOUT\x10\x04\"'\n" +
	"\rAttachRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"s\n" +
	"\x0eAttachResponse\x129\n" +
	"\x06output\x18\x01 \x01(\v2\x1f.rafiki.executor.v1.OutputChunkH\x00R\x06output\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCodeB\a\n" +
	"\x05event\"(\n" +
	"\rCancelRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"\x10\n" +
	"\x0eCancelResponse\"h\n" +
	"\x05Mount\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xeb\x02\n" +
	"\x10ProvisionRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12%\n" +
	"\x0eworkspace_mode\x18\x02 \x01(\tR\rworkspaceMode\x121\n" +
	"\x06mounts\x18\x03 \x03(\v2\x19.rafiki.executor.v1.MountR\x06mounts\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x03R\vmemoryBytes\x12\x12\n" +
	"\x04cpus\x18\a \x01(\x01R\x04cpus\x12?\n" +
	"\x03env\x18\b \x03(\v2-.rafiki.executor.v1.ProvisionRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x11ProvisionResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05roots\x18\x02 \x03(\tR\x05roots\x12\x18\n" +
	"\aworkdir\x18\x03 \x01(\tR\aworkdir\x12\x1c\n" +
	"\tisolation\x18\x04 \x01(\tR\tisolation\"3\n" +
	"\x0eReleaseRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\x11\n" +
	"\x0fReleaseResponse\":\n" +
	"\x15ProjectContextRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"=\n" +
	"\x16ProjectContextResponse\x12#\n" +
	"\rcontext_files\x18\x01 \x01(\tR\fcontextFiles\"9\n" +
	"\x14ProjectSkillsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"V\n" +
	"\fProjectSkill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\"Q\n" +
	"\x15ProjectSkillsResponse\x128\n" +
	"\x06skills\x18\x01 \x03(\v2 .rafiki.executor.v1.ProjectSkillR\x06skills\"I\n" +
	"\x10SkillBodyRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"9\n" +
	"\x11SkillBodyResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\"@\n" +
	"\x10JobOutputRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x03R\x05since\"\x88\x01\n" +
	"\x11JobOutputResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x16\n" +
	"\x06exited\x18\x03 \x01(\bR\x06exited\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found\"\xda\x01\n" +
	"\n" +
	"ProxyStart\x12\x1d\n" +
	"\n" +
	"proxy_name\x18\x01 \x01(\tR\tproxyName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12E\n" +
	"\aheaders\x18\x04 \x03(\v2+.rafiki.executor.v1.ProxyStart.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\fProxyRequest\x126\n" +
	"\x05start\x18\x01 \x01(\v2\x1e.rafiki.executor.v1.ProxyStartH\x00R\x05start\x12\x14\n" +
	"\x04body\x18\x02 \x01(\fH\x00R\x04bodyB\x05\n" +
	"\x03msg\"\xa5\x01\n" +
	"\tProxyHead\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12D\n" +
	"\aheaders\x18\x02 \x03(\v2*.rafiki.executor.v1.ProxyHead.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\rProxyResponse\x123\n" +
	"\x04head\x18\x01 \x01(\v2\x1d.rafiki.executor.v1.ProxyHeadH\x00R\x04head\x12\x14\n" +
	"\x04body\x18\x02 \x01(\fH\x00R\x04bodyB\x05\n" +
	"\x03msg2\xb6\b\n" +
	"\x0fExecutorService\x12U\n" +
	"\bDescribe\x12#.rafiki.executor.v1.DescribeRequest\x1a$.rafiki.executor.v1.DescribeResponse\x12O\n" +
	"\x06Health\x12!.rafiki.executor.v1.HealthRequest\x1a\".rafiki.executor.v1.HealthResponse\x12T\n" +
	"\aExecute\x12\".rafiki.executor.v1.ExecuteRequest\x1a#.rafiki.executor.v1.ExecuteResponse0\x01\x12Q\n" +
	"\x06Attach\x12!.rafiki.executor.v1.AttachRequest\x1a\".rafiki.executor.v1.AttachResponse0\x01\x12O\n" +
	"\x06Cancel\x12!.rafiki.executor.v1.CancelRequest\x1a\".rafiki.executor.v1.CancelResponse\x12X\n" +
	"\tJobOutput\x12$.rafiki.executor.v1.JobOutputRequest\x1a%.rafiki.executor.v1.JobOutputResponse\x12X\n" +
	"\tProvision\x12$.rafiki.executor.v1.ProvisionRequest\x1a%.rafiki.executor.v1.ProvisionResponse\x12R\n" +
	"\aRelease\x12\".rafiki.executor.v1.ReleaseRequest\x1a#.rafiki.executor.v1.ReleaseResponse\x12g\n" +
	"\x0eProjectContext\x12).rafiki.executor.v1.ProjectContextRequest\x1a*.rafiki.executor.v1.ProjectContextResponse\x12d\n" +
	"\rProjectSkills\x12(.rafiki.executor.v1.ProjectSkillsRequest\x1a).rafiki.executor.v1.ProjectSkillsResponse\x12X\n" +
	"\tSkillBody\x12$.rafiki.executor.v1.SkillBodyRequest\x1a%.rafiki.executor.v1.SkillBodyResponse\x12P\n" +
	"\x05Proxy\x12 .rafiki.executor.v1.ProxyRequest\x1a!.rafiki.executor.v1.ProxyResponse(\x010\x01B3Z1go.graveland.dev/rafiki/pkg/executorpb;executorpbb\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_executor_proto_goTypes = []any{
	(Failure_Code)(0),              // 0: rafiki.executor.v1.Failure.Code
	(*DescribeRequest)(nil),        // 1: rafiki.executor.v1.DescribeRequest
	(*DescribeResponse)(nil),       // 2: rafiki.executor.v1.DescribeResponse
	(*HealthRequest)(nil),          // 3: rafiki.executor.v1.HealthRequest
	(*HealthResponse)(nil),         // 4: rafiki.executor.v1.HealthResponse
	(*ContentBlock)(nil),           // 5: rafiki.executor.v1.ContentBlock
	(*ImageBlock)(nil),             // 6: rafiki.executor.v1.ImageBlock
	(*ExecuteRequest)(nil),         // 7: rafiki.executor.v1.ExecuteRequest
	(*ExecuteResponse)(nil),        // 8: rafiki.executor.v1.ExecuteResponse
	(*OutputChunk)(nil),            // 9: rafiki.executor.v1.OutputChunk
	(*Result)(nil),                 // 10: rafiki.executor.v1.Result
	(*Failure)(nil),                // 11: rafiki.executor.v1.Failure
	(*AttachRequest)(nil),          // 12: rafiki.executor.v1.AttachRequest
	(*AttachResponse)(nil),         // 13: rafiki.executor.v1.AttachResponse
	(*CancelRequest)(nil),          // 14: rafiki.executor.v1.CancelRequest
	(*CancelResponse)(nil),         // 15: rafiki.executor.v1.CancelResponse
	(*Mount)(nil),                  // 16: rafiki.executor.v1.Mount
	(*ProvisionRequest)(nil),       // 17: rafiki.executor.v1.ProvisionRequest
	(*ProvisionResponse)(nil),      // 18: rafiki.executor.v1.ProvisionResponse
	(*ReleaseRequest)(nil),         // 19: rafiki.executor.v1.ReleaseRequest
	(*ReleaseResponse)(nil),        // 20: rafiki.executor.v1.ReleaseResponse
	(*ProjectContextRequest)(nil),  // 21: rafiki.executor.v1.ProjectContextRequest
	(*ProjectContextResponse)(nil), // 22: rafiki.executor.v1.ProjectContextResponse
	(*ProjectSkillsRequest)(nil),   // 23: rafiki.executor.v1.ProjectSkillsRequest
	(*ProjectSkill)(nil),           // 24: rafiki.executor.v1.ProjectSkill
	(*ProjectSkillsResponse)(nil),  // 25: rafiki.executor.v1.ProjectSkillsResponse
	(*SkillBodyRequest)(nil),       // 26: rafiki.executor.v1.SkillBodyRequest
	(*SkillBodyResponse)(nil),      // 27: rafiki.executor.v1.SkillBodyResponse
	(*JobOutputRequest)(nil),       // 28: rafiki.executor.v1.JobOutputRequest
	(*JobOutputResponse)(nil),      // 29: rafiki.executor.v1.JobOutputResponse
	(*ProxyStart)(nil),             // 30: rafiki.executor.v1.ProxyStart
	(*ProxyRequest)(nil),           // 31: rafiki.executor.v1.ProxyRequest
	(*ProxyHead)(nil),              // 32: rafiki.executor.v1.ProxyHead
	(*ProxyResponse)(nil),          // 33: rafiki.executor.v1.ProxyResponse
	nil,                            // 34: rafiki.executor.v1.DescribeResponse.SelfReportedLabelsEntry
	nil,                            // 35: rafiki.executor.v1.ExecuteRequest.ExpectMtimeEntry
	nil,                            // 36: rafiki.executor.v1.Result.ObservedMtimeEntry
	nil,                            // 37: rafiki.executor.v1.ProvisionRequest.EnvEntry
	nil,                            // 38: rafiki.executor.v1.ProxyStart.HeadersEntry
	nil,                            // 39: rafiki.executor.v1.ProxyHead.HeadersEntry
}
var file_executor_proto_depIdxs = []int32{
	34, // 0: rafiki.executor.v1.DescribeResponse.self_reported_labels:type_name -> rafiki.executor.v1.DescribeResponse.SelfReportedLabelsEntry
	6,  // 1: rafiki.executor.v1.ContentBlock.image:type_name -> rafiki.executor.v1.ImageBlock
	35, // 2: rafiki.executor.v1.ExecuteRequest.expect_mtime:type_name -> rafiki.executor.v1.ExecuteRequest.ExpectMtimeEntry
	9,  // 3: rafiki.executor.v1.ExecuteResponse.output:type_name -> rafiki.executor.v1.OutputChunk
	10, // 4: rafiki.executor.v1.ExecuteResponse.result:type_name -> rafiki.executor.v1.Result
	11, // 5: rafiki.executor.v1.ExecuteResponse.failed:type_name -> rafiki.executor.v1.Failure
	5,  // 6: rafiki.executor.v1.Result.content:type_name -> rafiki.executor.v1.ContentBlock
	36, // 7: rafiki.executor.v1.Result.observed_mtime:type_name -> rafiki.executor.v1.Result.ObservedMtimeEntry
	0,  // 8: rafiki.executor.v1.Failure.code:type_name -> rafiki.executor.v1.Failure.Code
	9,  // 9: rafiki.executor.v1.AttachResponse.output:type_name -> rafiki.executor.v1.OutputChunk
	16, // 10: rafiki.executor.v1.ProvisionRequest.mounts:type_name -> rafiki.executor.v1.Mount
	37, // 11: rafiki.executor.v1.ProvisionRequest.env:type_name -> rafiki.executor.v1.ProvisionRequest.EnvEntry
	24, // 12: rafiki.executor.v1.ProjectSkillsResponse.skills:type_name -> rafiki.executor.v1.ProjectSkill
	38, // 13: rafiki.executor.v1.ProxyStart.headers:type_name -> rafiki.executor.v1.ProxyStart.HeadersEntry
	30, // 14: rafiki.executor.v1.ProxyRequest.start:type_name -> rafiki.executor.v1.ProxyStart
	39, // 15: rafiki.executor.v1.ProxyHead.headers:type_name -> rafiki.executor.v1.ProxyHead.HeadersEntry
	32, // 16: rafiki.executor.v1.ProxyResponse.head:type_name -> rafiki.executor.v1.ProxyHead
	1,  // 17: rafiki.executor.v1.ExecutorService.Describe:input_type -> rafiki.executor.v1.DescribeRequest
	3,  // 18: rafiki.executor.v1.ExecutorService.Health:input_type -> rafiki.executor.v1.HealthRequest
	7,  // 19: rafiki.executor.v1.ExecutorService.Execute:input_type -> rafiki.executor.v1.ExecuteRequest
	12, // 20: rafiki.executor.v1.ExecutorService.Attach:input_type -> rafiki.executor.v1.AttachRequest
	14, // 21: rafiki.executor.v1.ExecutorService.Cancel:input_type -> rafiki.executor.v1.CancelRequest
	28, // 22: rafiki.executor.v1.ExecutorService.JobOutput:input_type -> rafiki.executor.v1.JobOutputRequest
	17, // 23: rafiki.executor.v1.ExecutorService.Provision:input_type -> rafiki.executor.v1.ProvisionRequest
	19, // 24: rafiki.executor.v1.ExecutorService.Release:input_type -> rafiki.executor.v1.ReleaseRequest
	21, // 25: rafiki.executor.v1.ExecutorService.ProjectContext:input_type -> rafiki.executor.v1.ProjectContextRequest
	23, // 26: rafiki.executor.v1.ExecutorService.ProjectSkills:input_type -> rafiki.executor.v1.ProjectSkillsRequest
	26, // 27: rafiki.executor.v1.ExecutorService.SkillBody:input_type -> rafiki.executor.v1.SkillBodyRequest
	31, // 28: rafiki.executor.v1.ExecutorService.Proxy:input_type -> rafiki.executor.v1.ProxyRequest
	2,  // 29: rafiki.executor.v1.ExecutorService.Describe:output_type -> rafiki.executor.v1.DescribeResponse
	4,  // 30: rafiki.executor.v1.ExecutorService.Health:output_type -> rafiki.executor.v1.HealthResponse
	8,  // 31: rafiki.executor.v1.ExecutorService.Execute:output_type -> rafiki.executor.v1.ExecuteResponse
	13, // 32: rafiki.executor.v1.ExecutorService.Attach:output_type -> rafiki.executor.v1.AttachResponse
	15, // 33: rafiki.executor.v1.ExecutorService.Cancel:output_type -> rafiki.executor.v1.CancelResponse
	29, // 34: rafiki.executor.v1.ExecutorService.JobOutput:output_type -> rafiki.executor.v1.JobOutputResponse
	18, // 35: rafiki.executor.v1.ExecutorService.Provision:output_type -> rafiki.executor.v1.ProvisionResponse
	20, // 36: rafiki.executor.v1.ExecutorService.Release:output_type -> rafiki.executor.v1.ReleaseResponse
	22, // 37: rafiki.executor.v1.ExecutorService.ProjectContext:output_type -> rafiki.executor.v1.ProjectContextResponse
	25, // 38: rafiki.executor.v1.ExecutorService.ProjectSkills:output_type -> rafiki.executor.v1.ProjectSkillsResponse
	27, // 39: rafiki.executor.v1.ExecutorService.SkillBody:output_type -> rafiki.executor.v1.SkillBodyResponse
	33, // 40: rafiki.executor.v1.ExecutorService.Proxy:output_type -> rafiki.executor.v1.ProxyResponse
	29, // [29:41] is the sub-list for method output_type
	17, // [17:29] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	file_executor_proto_msgTypes[4].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
		(*ContentBlock_Image)(nil),
	}
	file_executor_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecuteResponse_Output)(nil),
		(*ExecuteResponse_Result)(nil),
		(*ExecuteResponse_Failed)(nil),
		(*ExecuteResponse_Handle)(nil),
	}
	file_executor_proto_msgTypes[12].OneofWrappers = []any{
		(*AttachResponse_Output)(nil),
		(*AttachResponse_ExitCode)(nil),
	}
	file_executor_proto_msgTypes[30].OneofWrappers = []any{
		(*ProxyRequest_Start)(nil),
		(*ProxyRequest_Body)(nil),
	}
	file_executor_proto_msgTypes[32].OneofWrappers = []any{
		(*ProxyResponse_Head)(nil),
		(*ProxyResponse_Body)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		EnumInfos:         file_executor_proto_enumTypes,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
