// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rafiki/daraja/v1/daraja.proto

package darajapbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	darajapb "go.graveland.dev/rafiki/pkg/darajapb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DarajaServiceName is the fully-qualified name of the DarajaService service.
	DarajaServiceName = "rafiki.daraja.v1.DarajaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DarajaServiceRelayProcedure is the fully-qualified name of the DarajaService's Relay RPC.
	DarajaServiceRelayProcedure = "/rafiki.daraja.v1.DarajaService/Relay"
	// DarajaServiceRestartProcedure is the fully-qualified name of the DarajaService's Restart RPC.
	DarajaServiceRestartProcedure = "/rafiki.daraja.v1.DarajaService/Restart"
	// DarajaServiceShutdownProcedure is the fully-qualified name of the DarajaService's Shutdown RPC.
	DarajaServiceShutdownProcedure = "/rafiki.daraja.v1.DarajaService/Shutdown"
	// DarajaServiceHealthProcedure is the fully-qualified name of the DarajaService's Health RPC.
	DarajaServiceHealthProcedure = "/rafiki.daraja.v1.DarajaService/Health"
)

// DarajaServiceClient is a client for the rafiki.daraja.v1.DarajaService service.
type DarajaServiceClient interface {
	// Relay carries the child's stdio in both directions. One stream for the
	// host's lifetime — it deliberately SURVIVES a Restart, because the consumer
	// keeps per-child state across an abort and tearing the stream down would
	// discard it.
	Relay(context.Context) *connect.BidiStreamForClient[darajapb.RelayRequest, darajapb.RelayResponse]
	// Restart replaces the child process: signal, wait for exit, launch again
	// with the supplied argv. ONE verb rather than Stop plus Launch, because the
	// invariant that makes a 1:1 host simple is that a daraja always has exactly
	// one child; splitting it creates a childless daraja that then needs
	// representing, timing out and reaping.
	Restart(context.Context, *connect.Request[darajapb.RestartRequest]) (*connect.Response[darajapb.RestartResponse], error)
	// Shutdown ends the child and then daraja exits, preserving the same
	// invariant from the other side.
	Shutdown(context.Context, *connect.Request[darajapb.ShutdownRequest]) (*connect.Response[darajapb.ShutdownResponse], error)
	Health(context.Context, *connect.Request[darajapb.HealthRequest]) (*connect.Response[darajapb.HealthResponse], error)
}

// NewDarajaServiceClient constructs a client for the rafiki.daraja.v1.DarajaService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDarajaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DarajaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	darajaServiceMethods := darajapb.File_rafiki_daraja_v1_daraja_proto.Services().ByName("DarajaService").Methods()
	return &darajaServiceClient{
		relay: connect.NewClient[darajapb.RelayRequest, darajapb.RelayResponse](
			httpClient,
			baseURL+DarajaServiceRelayProcedure,
			connect.WithSchema(darajaServiceMethods.ByName("Relay")),
			connect.WithClientOptions(opts...),
		),
		restart: connect.NewClient[darajapb.RestartRequest, darajapb.RestartResponse](
			httpClient,
			baseURL+DarajaServiceRestartProcedure,
			connect.WithSchema(darajaServiceMethods.ByName("Restart")),
			connect.WithClientOptions(opts...),
		),
		shutdown: connect.NewClient[darajapb.ShutdownRequest, darajapb.ShutdownResponse](
			httpClient,
			baseURL+DarajaServiceShutdownProcedure,
			connect.WithSchema(darajaServiceMethods.ByName("Shutdown")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[darajapb.HealthRequest, darajapb.HealthResponse](
			httpClient,
			baseURL+DarajaServiceHealthProcedure,
			connect.WithSchema(darajaServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
	}
}

// darajaServiceClient implements DarajaServiceClient.
type darajaServiceClient struct {
	relay    *connect.Client[darajapb.RelayRequest, darajapb.RelayResponse]
	restart  *connect.Client[darajapb.RestartRequest, darajapb.RestartResponse]
	shutdown *connect.Client[darajapb.ShutdownRequest, darajapb.ShutdownResponse]
	health   *connect.Client[darajapb.HealthRequest, darajapb.HealthResponse]
}

// Relay calls rafiki.daraja.v1.DarajaService.Relay.
func (c *darajaServiceClient) Relay(ctx context.Context) *connect.BidiStreamForClient[darajapb.RelayRequest, darajapb.RelayResponse] {
	return c.relay.CallBidiStream(ctx)
}

// Restart calls rafiki.daraja.v1.DarajaService.Restart.
func (c *darajaServiceClient) Restart(ctx context.Context, req *connect.Request[darajapb.RestartRequest]) (*connect.Response[darajapb.RestartResponse], error) {
	return c.restart.CallUnary(ctx, req)
}

// Shutdown calls rafiki.daraja.v1.DarajaService.Shutdown.
func (c *darajaServiceClient) Shutdown(ctx context.Context, req *connect.Request[darajapb.ShutdownRequest]) (*connect.Response[darajapb.ShutdownResponse], error) {
	return c.shutdown.CallUnary(ctx, req)
}

// Health calls rafiki.daraja.v1.DarajaService.Health.
func (c *darajaServiceClient) Health(ctx context.Context, req *connect.Request[darajapb.HealthRequest]) (*connect.Response[darajapb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// DarajaServiceHandler is an implementation of the rafiki.daraja.v1.DarajaService service.
type DarajaServiceHandler interface {
	// Relay carries the child's stdio in both directions. One stream for the
	// host's lifetime — it deliberately SURVIVES a Restart, because the consumer
	// keeps per-child state across an abort and tearing the stream down would
	// discard it.
	Relay(context.Context, *connect.BidiStream[darajapb.RelayRequest, darajapb.RelayResponse]) error
	// Restart replaces the child process: signal, wait for exit, launch again
	// with the supplied argv. ONE verb rather than Stop plus Launch, because the
	// invariant that makes a 1:1 host simple is that a daraja always has exactly
	// one child; splitting it creates a childless daraja that then needs
	// representing, timing out and reaping.
	Restart(context.Context, *connect.Request[darajapb.RestartRequest]) (*connect.Response[darajapb.RestartResponse], error)
	// Shutdown ends the child and then daraja exits, preserving the same
	// invariant from the other side.
	Shutdown(context.Context, *connect.Request[darajapb.ShutdownRequest]) (*connect.Response[darajapb.ShutdownResponse], error)
	Health(context.Context, *connect.Request[darajapb.HealthRequest]) (*connect.Response[darajapb.HealthResponse], error)
}

// NewDarajaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDarajaServiceHandler(svc DarajaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	darajaServiceMethods := darajapb.File_rafiki_daraja_v1_daraja_proto.Services().ByName("DarajaService").Methods()
	darajaServiceRelayHandler := connect.NewBidiStreamHandler(
		DarajaServiceRelayProcedure,
		svc.Relay,
		connect.WithSchema(darajaServiceMethods.ByName("Relay")),
		connect.WithHandlerOptions(opts...),
	)
	darajaServiceRestartHandler := connect.NewUnaryHandler(
		DarajaServiceRestartProcedure,
		svc.Restart,
		connect.WithSchema(darajaServiceMethods.ByName("Restart")),
		connect.WithHandlerOptions(opts...),
	)
	darajaServiceShutdownHandler := connect.NewUnaryHandler(
		DarajaServiceShutdownProcedure,
		svc.Shutdown,
		connect.WithSchema(darajaServiceMethods.ByName("Shutdown")),
		connect.WithHandlerOptions(opts...),
	)
	darajaServiceHealthHandler := connect.NewUnaryHandler(
		DarajaServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(darajaServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rafiki.daraja.v1.DarajaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DarajaServiceRelayProcedure:
			darajaServiceRelayHandler.ServeHTTP(w, r)
		case DarajaServiceRestartProcedure:
			darajaServiceRestartHandler.ServeHTTP(w, r)
		case DarajaServiceShutdownProcedure:
			darajaServiceShutdownHandler.ServeHTTP(w, r)
		case DarajaServiceHealthProcedure:
			darajaServiceHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDarajaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDarajaServiceHandler struct{}

func (UnimplementedDarajaServiceHandler) Relay(context.Context, *connect.BidiStream[darajapb.RelayRequest, darajapb.RelayResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.daraja.v1.DarajaService.Relay is not implemented"))
}

func (UnimplementedDarajaServiceHandler) Restart(context.Context, *connect.Request[darajapb.RestartRequest]) (*connect.Response[darajapb.RestartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.daraja.v1.DarajaService.Restart is not implemented"))
}

func (UnimplementedDarajaServiceHandler) Shutdown(context.Context, *connect.Request[darajapb.ShutdownRequest]) (*connect.Response[darajapb.ShutdownResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.daraja.v1.DarajaService.Shutdown is not implemented"))
}

func (UnimplementedDarajaServiceHandler) Health(context.Context, *connect.Request[darajapb.HealthRequest]) (*connect.Response[darajapb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rafiki.daraja.v1.DarajaService.Health is not implemented"))
}
