// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"
)

// pyReserved gets a trailing underscore when a proto field name collides:
// Python keywords, plus "self"/"cls" which are not keywords but collide with
// the receiver of every generated method.
var pyReserved = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true,
	"assert": true, "async": true, "await": true, "break": true, "class": true,
	"continue": true, "def": true, "del": true, "elif": true, "else": true,
	"except": true, "finally": true, "for": true, "from": true, "global": true,
	"if": true, "import": true, "in": true, "is": true, "lambda": true,
	"nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
	"self": true, "cls": true,
}

func pyAttr(name string) string {
	if pyReserved[name] {
		return name + "_"
	}
	return name
}

// genField is one proto field resolved for rendering.
type genField struct {
	attr  string // Python attribute name
	wire  string // JSON key exactly as protoc computes it (lowerCamelCase)
	kind  string // codec tag, see kindOf
	oneof string // real oneof name, or "" — proto3 `optional` rides a
	//                synthetic oneof protoc names "_"+field, which is presence,
	//                not a oneof group
	presence bool // the field tracks presence: proto3 optional, a oneof
	//                arm, or a message field. Such fields render
	//                Optional[...] = None and are emitted only when set.
}

// renderModule renders one generated module: header, imports, SERVICE
// constants, then every enum and message in file order, and the small helper
// functions the codec methods share.
func renderModule(fd *descriptorpb.FileDescriptorProto, reg *registry) string {
	currentModule = moduleName(fd.GetName())
	var b strings.Builder
	fmt.Fprintf(&b, `"""Generated by protoc-gen-rafikipy from %s — do not edit.

Regenerate with make proto. The classes speak the Connect JSON codec:
lowerCamelCase keys, enums as their proto names, 64-bit integers as strings
(decoded from strings or numbers too), bytes as base64. A dataclass field
whose proto field is optional or belongs to a oneof is Optional[...] = None.
"""
from __future__ import annotations

import base64
import binascii
import dataclasses
import math
from typing import Optional

`, fd.GetName())

	// Sibling-module imports, only when actually referenced.
	deps := map[string]bool{}
	for _, m := range fd.GetMessageType() {
		collectDeps(m, reg, currentModule, deps)
	}
	names := make([]string, 0, len(deps))
	for d := range deps {
		names = append(names, d)
	}
	sort.Strings(names)
	for _, d := range names {
		fmt.Fprintf(&b, "from . import %s\n", d)
	}
	if len(names) > 0 {
		b.WriteString("\n")
	}

	for _, s := range fd.GetService() {
		svc := s.GetName()
		if fd.GetPackage() != "" {
			svc = fd.GetPackage() + "." + svc
		}
		fmt.Fprintf(&b, "SERVICE_%s = %q\n", strings.ToUpper(s.GetName()), svc)
	}
	if len(fd.GetService()) > 0 {
		b.WriteString("\n")
	}

	for _, e := range fd.GetEnumType() {
		renderEnum(&b, e, "")
	}
	for _, m := range fd.GetMessageType() {
		renderMessage(&b, m, reg, m.GetName(), "")
	}
	b.WriteString(moduleHelpers)
	return b.String()
}

// moduleHelpers is appended to every generated module: the base64/int/float
// conversions to_dict and from_dict reference.
const moduleHelpers = `

def _b64_out(value: bytes) -> str:
    """bytes → base64 with padding, the protobuf JSON encoding."""
    return base64.b64encode(value).decode("ascii")


def _b64_in(value) -> bytes:
    """base64 → bytes, accepting standard and URL-safe alphabets and any
    padding, exactly as the protobuf JSON decoder must."""
    if not isinstance(value, str):
        raise TypeError("expected base64 string for a bytes field")
    normalized = value.replace("-", "+").replace("_", "/")
    if len(normalized) % 4:
        normalized += "=" * (4 - len(normalized) % 4)
    try:
        return base64.b64decode(normalized, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise ValueError("invalid base64 in bytes field") from exc


def _int_in(value) -> int:
    """A wire integer → int. 64-bit integers travel as strings; 32-bit ones
    as numbers. Both spellings are accepted for either."""
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str):
        try:
            return int(value)
        except ValueError:
            return int(float(value))
    raise TypeError("expected an integer (number or string) on the wire")


def _float_out(value: float):
    """A wire float: the number itself, except non-finite values, which the
    protobuf JSON encoding spells as strings."""
    if math.isnan(value):
        return "NaN"
    if math.isinf(value):
        return "Infinity" if value > 0 else "-Infinity"
    return value


def _float_in(value) -> float:
    """A wire float → Python float, accepting the non-finite strings too."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    if isinstance(value, str):
        if value == "NaN":
            return math.nan
        if value == "Infinity":
            return math.inf
        if value == "-Infinity":
            return -math.inf
        return float(value)
    raise TypeError("expected a number (or non-finite string) on the wire")
`

// collectDeps walks a message tree recording which sibling modules its fields
// reference, so the module imports exactly what it needs.
func collectDeps(m *descriptorpb.DescriptorProto, reg *registry, module string, deps map[string]bool) {
	for _, f := range m.GetField() {
		if t := f.GetType(); t == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE ||
			t == descriptorpb.FieldDescriptorProto_TYPE_ENUM {
			if ref := reg.byFQ[f.GetTypeName()]; ref != nil && ref.module != module {
				deps[ref.module] = true
			}
		}
	}
	for _, nested := range m.GetNestedType() {
		if nested.GetOptions().GetMapEntry() {
			continue
		}
		collectDeps(nested, reg, module, deps)
	}
}

// renderEnum emits one enum constants class at the given indentation.
func renderEnum(b *strings.Builder, e *descriptorpb.EnumDescriptorProto, indent string) {
	fmt.Fprintf(b, "%sclass %s:\n", indent, e.GetName())
	for _, v := range e.GetValue() {
		fmt.Fprintf(b, "%s    %s = %q\n", indent, pyAttr(v.GetName()), v.GetName())
	}
	fmt.Fprintf(b, "%s\n", indent)
}

// renderMessage emits one message as a dataclass, its codec methods, then its
// nested enums and messages. path is the message's Python path within the
// module, threaded down so nested classes can name themselves; indent nests
// nested classes inside their parent, so a nested message is reachable as
// Parent.Child exactly as the proto scopes it.
func renderMessage(b *strings.Builder, m *descriptorpb.DescriptorProto, reg *registry, path, indent string) {
	fields := resolveFields(m, reg)
	nested := nonEntryNested(m)

	fmt.Fprintf(b, "%s@dataclasses.dataclass\n%sclass %s:\n", indent, indent, m.GetName())
	if len(fields) == 0 {
		fmt.Fprintf(b, "%s    pass\n", indent)
	} else {
		for _, f := range fields {
			fmt.Fprintf(b, "%s    %s: %s\n", indent, f.attr, annotationOf(f))
		}
	}
	// The codec is emitted even for field-less messages: a response class
	// every caller decodes with from_dict keeps the call sites uniform.
	fmt.Fprintf(b, "\n")
	renderToDict(b, m, path, fields, indent)
	renderFromDict(b, path, fields, indent)
	fmt.Fprintf(b, "%s\n", indent)

	for _, e := range m.GetEnumType() {
		renderEnum(b, e, indent+"    ")
	}
	for _, n := range nested {
		renderMessage(b, n, reg, path+"."+n.GetName(), indent+"    ")
	}
}

// nonEntryNested lists a message's nested messages that are not map entries.
func nonEntryNested(m *descriptorpb.DescriptorProto) []*descriptorpb.DescriptorProto {
	var out []*descriptorpb.DescriptorProto
	for _, n := range m.GetNestedType() {
		if !n.GetOptions().GetMapEntry() {
			out = append(out, n)
		}
	}
	return out
}

// resolveFields converts a message's proto fields to the generated shape.
func resolveFields(m *descriptorpb.DescriptorProto, reg *registry) []genField {
	realOneofs := map[int32]string{}
	for i, o := range m.GetOneofDecl() {
		// Synthetic oneofs (protoc names them "_"+field) back proto3
		// optional fields and are presence, not oneofs.
		if !strings.HasPrefix(o.GetName(), "_") {
			realOneofs[int32(i)] = o.GetName()
		}
	}
	var out []genField
	for _, f := range m.GetField() {
		oneof := ""
		if f.OneofIndex != nil && !f.GetProto3Optional() {
			oneof = realOneofs[f.GetOneofIndex()]
		}
		kind := kindOf(f, reg)
		out = append(out, genField{
			attr:  pyAttr(f.GetName()),
			wire:  f.GetJsonName(),
			kind:  kind,
			oneof: oneof,
			presence: f.GetProto3Optional() || oneof != "" ||
				strings.HasPrefix(kind, "msg:"),
		})
	}
	return out
}

// kindOf tags a field for the generated codec: "str", "bytes", "bool",
// "int32", "int64", "float", "enum:ZERO_NAME", "msg:Python.Path",
// "list:<inner>", "map:<inner>".
func kindOf(f *descriptorpb.FieldDescriptorProto, reg *registry) string {
	if f.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
		if entry := reg.entries[f.GetTypeName()]; entry != nil {
			return "map:" + elemKind(entry.value, reg)
		}
	}
	if f.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED {
		return "list:" + elemKind(f, reg)
	}
	if k := scalarKind(f, reg); k != "" {
		return k
	}
	return messageRef(f, reg)
}

func elemKind(f *descriptorpb.FieldDescriptorProto, reg *registry) string {
	if k := scalarKind(f, reg); k != "" {
		return k
	}
	return messageRef(f, reg)
}

func scalarKind(f *descriptorpb.FieldDescriptorProto, reg *registry) string {
	switch f.GetType() {
	case descriptorpb.FieldDescriptorProto_TYPE_STRING:
		return "str"
	case descriptorpb.FieldDescriptorProto_TYPE_BYTES:
		return "bytes"
	case descriptorpb.FieldDescriptorProto_TYPE_BOOL:
		return "bool"
	case descriptorpb.FieldDescriptorProto_TYPE_INT32,
		descriptorpb.FieldDescriptorProto_TYPE_SINT32,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED32,
		descriptorpb.FieldDescriptorProto_TYPE_UINT32:
		return "int32"
	case descriptorpb.FieldDescriptorProto_TYPE_INT64,
		descriptorpb.FieldDescriptorProto_TYPE_SINT64,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED64,
		descriptorpb.FieldDescriptorProto_TYPE_UINT64:
		return "int64"
	case descriptorpb.FieldDescriptorProto_TYPE_FLOAT,
		descriptorpb.FieldDescriptorProto_TYPE_DOUBLE:
		return "float"
	case descriptorpb.FieldDescriptorProto_TYPE_ENUM:
		zero := ""
		if info := reg.enumVal[f.GetTypeName()]; info != nil {
			zero = info.zero
		}
		return "enum:" + zero
	default:
		return ""
	}
}

// messageRef renders the Python path to a message's class, module-qualified
// when the class lives in a sibling generated module.
func messageRef(f *descriptorpb.FieldDescriptorProto, reg *registry) string {
	ref := reg.byFQ[f.GetTypeName()]
	if ref == nil {
		return "msg:UNKNOWN"
	}
	if ref.module == currentModule {
		return "msg:" + ref.path
	}
	return "msg:" + ref.module + "." + ref.path
}

// currentModule is the module being rendered; messageRef compares against it.
var currentModule string

// ─── Python rendering ────────────────────────────────────────────────────────

// annotationOf renders the dataclass annotation for one field.
func annotationOf(f genField) string {
	switch {
	case strings.HasPrefix(f.kind, "list:"):
		inner := annotationForKind(strings.TrimPrefix(f.kind, "list:"))
		return fmt.Sprintf("list[%s] = dataclasses.field(default_factory=list)", inner)
	case strings.HasPrefix(f.kind, "map:"):
		inner := annotationForKind(strings.TrimPrefix(f.kind, "map:"))
		return fmt.Sprintf("dict[str, %s] = dataclasses.field(default_factory=dict)", inner)
	case f.presence:
		return fmt.Sprintf("Optional[%s] = None", annotationForKind(f.kind))
	default:
		return fmt.Sprintf("%s = %s", annotationForKind(f.kind), defaultOf(f))
	}
}

func annotationForKind(kind string) string {
	switch {
	case kind == "str":
		return "str"
	case kind == "bytes":
		return "bytes"
	case kind == "bool":
		return "bool"
	case kind == "int32" || kind == "int64":
		return "int"
	case kind == "float":
		return "float"
	case strings.HasPrefix(kind, "enum:"):
		return "str"
	case strings.HasPrefix(kind, "msg:"):
		return strings.TrimPrefix(kind, "msg:")
	default:
		return "object"
	}
}

// defaultOf renders the dataclass default for a plain (no-presence) field:
// the Python zero matching the proto zero.
func defaultOf(f genField) string {
	switch {
	case f.kind == "str":
		return `""`
	case strings.HasPrefix(f.kind, "enum:"):
		return `"` + strings.TrimPrefix(f.kind, "enum:") + `"`
	case f.kind == "bytes":
		return `b""`
	case f.kind == "bool":
		return "False"
	case f.kind == "int32" || f.kind == "int64":
		return "0"
	case f.kind == "float":
		return "0.0"
	default:
		return "None"
	}
}

// emitExpr renders the Python expression that turns a field value into its
// wire shape. name is the Python expression holding the value.
func emitExpr(f genField, name string) string {
	switch {
	case strings.HasPrefix(f.kind, "list:"):
		inner := strings.TrimPrefix(f.kind, "list:")
		return fmt.Sprintf("[%s for x in %s]", listElemExpr(inner, "x"), name)
	case strings.HasPrefix(f.kind, "map:"):
		inner := strings.TrimPrefix(f.kind, "map:")
		return fmt.Sprintf("dict((k, %s) for k, v in %s.items())", mapValueExpr(inner, "v"), name)
	case strings.HasPrefix(f.kind, "msg:"):
		return fmt.Sprintf("%s.to_dict()", name)
	case f.kind == "int64":
		return fmt.Sprintf("str(%s)", name)
	case f.kind == "float":
		return fmt.Sprintf("_float_out(%s)", name)
	case f.kind == "bytes":
		return fmt.Sprintf("_b64_out(%s)", name)
	default:
		return name
	}
}

func listElemExpr(kind, name string) string {
	if strings.HasPrefix(kind, "msg:") {
		return fmt.Sprintf("%s.to_dict()", name)
	}
	return encodeScalarExpr(kind, name)
}

func mapValueExpr(kind, name string) string {
	return encodeScalarExpr(kind, name)
}

func encodeScalarExpr(kind, name string) string {
	switch kind {
	case "int64":
		return fmt.Sprintf("str(%s)", name)
	case "float":
		return fmt.Sprintf("_float_out(%s)", name)
	case "bytes":
		return fmt.Sprintf("_b64_out(%s)", name)
	default:
		return name
	}
}

// decodeExpr renders the Python expression that turns a decoded JSON value
// into the field's Python value.
func decodeExpr(f genField, name string) string {
	switch {
	case strings.HasPrefix(f.kind, "list:"):
		inner := strings.TrimPrefix(f.kind, "list:")
		return fmt.Sprintf("[%s for x in %s]", listElemDecode(inner, "x"), name)
	case strings.HasPrefix(f.kind, "map:"):
		inner := strings.TrimPrefix(f.kind, "map:")
		return fmt.Sprintf("{k: %s for k, v in %s.items()}", mapValueDecode(inner, "v"), name)
	case strings.HasPrefix(f.kind, "msg:"):
		return fmt.Sprintf("%s.from_dict(%s)", strings.TrimPrefix(f.kind, "msg:"), name)
	case f.kind == "int32":
		return fmt.Sprintf("_int_in(%s)", name)
	case f.kind == "int64":
		return fmt.Sprintf("_int_in(%s)", name)
	case f.kind == "float":
		return fmt.Sprintf("_float_in(%s)", name)
	case f.kind == "bytes":
		return fmt.Sprintf("_b64_in(%s)", name)
	default:
		return name
	}
}

func listElemDecode(kind, name string) string {
	if strings.HasPrefix(kind, "msg:") {
		return fmt.Sprintf("%s.from_dict(%s)", strings.TrimPrefix(kind, "msg:"), name)
	}
	return decodeScalarExpr(kind, name)
}

func mapValueDecode(kind, name string) string {
	return decodeScalarExpr(kind, name)
}

func decodeScalarExpr(kind, name string) string {
	switch kind {
	case "int32", "int64":
		return fmt.Sprintf("_int_in(%s)", name)
	case "float":
		return fmt.Sprintf("_float_in(%s)", name)
	case "bytes":
		return fmt.Sprintf("_b64_in(%s)", name)
	default:
		return name
	}
}

// renderToDict emits to_dict: presence fields only when set, plain scalars
// only when non-zero, oneofs exactly one arm.
func renderToDict(b *strings.Builder, m *descriptorpb.DescriptorProto, path string, fields []genField, indent string) {
	fmt.Fprintf(b, "%s    def to_dict(self) -> dict:\n", indent)
	fmt.Fprintf(b, "%s        out = {}\n", indent)
	for _, f := range fields {
		switch {
		case f.oneof != "":
			// Emitted below, after a single set-arm check over the group.
		case strings.HasPrefix(f.kind, "list:"):
			fmt.Fprintf(b, "%s        if self.%s:\n%s            out[%q] = %s\n", indent, f.attr, indent, f.wire, emitExpr(f, "self."+f.attr))
		case strings.HasPrefix(f.kind, "map:"):
			fmt.Fprintf(b, "%s        if self.%s:\n%s            out[%q] = %s\n", indent, f.attr, indent, f.wire, emitExpr(f, "self."+f.attr))
		case f.presence:
			fmt.Fprintf(b, "%s        if self.%s is not None:\n%s            out[%q] = %s\n", indent, f.attr, indent, f.wire, emitExpr(f, "self."+f.attr))
		default:
			fmt.Fprintf(b, "%s        if self.%s != %s:\n%s            out[%q] = %s\n", indent, f.attr, defaultOf(f), indent, f.wire, emitExpr(f, "self."+f.attr))
		}
	}
	// Oneof groups: refuse two set arms rather than silently encoding one —
	// proto3's "setting one clears the others" has no dataclass equivalent,
	// and a silent pick would hide a caller bug.
	seen := map[string]bool{}
	for _, f := range fields {
		if f.oneof == "" || seen[f.oneof] {
			continue
		}
		seen[f.oneof] = true
		arms := make([]string, 0, 2)
		for _, g := range fields {
			if g.oneof == f.oneof {
				arms = append(arms, "self."+g.attr)
			}
		}
		fmt.Fprintf(b, "%s        _set_%s = [x for x in (%s) if x is not None]\n", indent, f.oneof, strings.Join(arms, ", "))
		fmt.Fprintf(b, "%s        if len(_set_%s) > 1:\n%s            raise ValueError(\"%s: at most one arm of oneof '%s' may be set\")\n", indent, f.oneof, indent, m.GetName(), f.oneof)
		for _, g := range fields {
			if g.oneof != f.oneof {
				continue
			}
			fmt.Fprintf(b, "%s        if self.%s is not None:\n%s            out[%q] = %s\n", indent, g.attr, indent, g.wire, emitExpr(g, "self."+g.attr))
		}
	}
	fmt.Fprintf(b, "%s        return out\n", indent)
}

// renderFromDict emits from_dict: per-field decode from the wire key,
// unknown keys ignored. The return annotation quotes the class path, which
// for nested classes is not yet bound when the module body executes — but
// annotations are strings under `from __future__ import annotations` and are
// never evaluated at import time.
func renderFromDict(b *strings.Builder, classPath string, fields []genField, indent string) {
	fmt.Fprintf(b, "%s    @classmethod\n", indent)
	fmt.Fprintf(b, "%s    def from_dict(cls, _d: dict) -> %q:\n", indent, classPath)
	fmt.Fprintf(b, "%s        obj = cls()\n", indent)
	for _, f := range fields {
		fmt.Fprintf(b, "%s        _v = _d.get(%q)\n", indent, f.wire)
		fmt.Fprintf(b, "%s        if _v is not None:\n%s            obj.%s = %s\n", indent, indent, f.attr, decodeExpr(f, "_v"))
	}
	fmt.Fprintf(b, "%s        return obj\n", indent)
}
