"""Generated by protoc-gen-rafikipy from rafiki/daraja/v1/daraja.proto — do not edit.

Regenerate with make proto. The classes speak the Connect JSON codec:
lowerCamelCase keys, enums as their proto names, 64-bit integers as strings
(decoded from strings or numbers too), bytes as base64. A dataclass field
whose proto field is optional or belongs to a oneof is Optional[...] = None.
"""
from __future__ import annotations

import base64
import binascii
import dataclasses
import math
from typing import Optional

SERVICE_DARAJASERVICE = "rafiki.daraja.v1.DarajaService"

class Kind:
    KIND_UNSPECIFIED = "KIND_UNSPECIFIED"
    KIND_CLAUDE = "KIND_CLAUDE"
    KIND_SCRIPT = "KIND_SCRIPT"

@dataclasses.dataclass
class RelayRequest:
    stdin: bytes = b""

    def to_dict(self) -> dict:
        out = {}
        if self.stdin != b"":
            out["stdin"] = _b64_out(self.stdin)
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "RelayRequest":
        obj = cls()
        _v = _d.get("stdin")
        if _v is not None:
            obj.stdin = _b64_in(_v)
        return obj

@dataclasses.dataclass
class RelayResponse:
    stdout: Optional[bytes] = None
    restarted: Optional[ProcessRestarted] = None
    exited: Optional[ProcessExited] = None
    stderr: Optional[bytes] = None

    def to_dict(self) -> dict:
        out = {}
        _set_event = [x for x in (self.stdout, self.restarted, self.exited, self.stderr) if x is not None]
        if len(_set_event) > 1:
            raise ValueError("RelayResponse: at most one arm of oneof 'event' may be set")
        if self.stdout is not None:
            out["stdout"] = _b64_out(self.stdout)
        if self.restarted is not None:
            out["restarted"] = self.restarted.to_dict()
        if self.exited is not None:
            out["exited"] = self.exited.to_dict()
        if self.stderr is not None:
            out["stderr"] = _b64_out(self.stderr)
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "RelayResponse":
        obj = cls()
        _v = _d.get("stdout")
        if _v is not None:
            obj.stdout = _b64_in(_v)
        _v = _d.get("restarted")
        if _v is not None:
            obj.restarted = ProcessRestarted.from_dict(_v)
        _v = _d.get("exited")
        if _v is not None:
            obj.exited = ProcessExited.from_dict(_v)
        _v = _d.get("stderr")
        if _v is not None:
            obj.stderr = _b64_in(_v)
        return obj

@dataclasses.dataclass
class ProcessRestarted:
    pid: int = 0

    def to_dict(self) -> dict:
        out = {}
        if self.pid != 0:
            out["pid"] = self.pid
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ProcessRestarted":
        obj = cls()
        _v = _d.get("pid")
        if _v is not None:
            obj.pid = _int_in(_v)
        return obj

@dataclasses.dataclass
class ProcessExited:
    exit_code: int = 0
    signal: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.exit_code != 0:
            out["exitCode"] = self.exit_code
        if self.signal != "":
            out["signal"] = self.signal
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ProcessExited":
        obj = cls()
        _v = _d.get("exitCode")
        if _v is not None:
            obj.exit_code = _int_in(_v)
        _v = _d.get("signal")
        if _v is not None:
            obj.signal = _v
        return obj

@dataclasses.dataclass
class ClaudeParams:
    model: str = ""
    resume_session: str = ""
    permission_mode: str = ""
    proxy_url: str = ""
    proxy_token: str = ""
    passthrough_auth: bool = False
    auto_compact_window: int = 0
    record_requests: bool = False
    append_system_prompt: str = ""
    extra_args: list[str] = dataclasses.field(default_factory=list)
    mcp_token: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.model != "":
            out["model"] = self.model
        if self.resume_session != "":
            out["resumeSession"] = self.resume_session
        if self.permission_mode != "":
            out["permissionMode"] = self.permission_mode
        if self.proxy_url != "":
            out["proxyUrl"] = self.proxy_url
        if self.proxy_token != "":
            out["proxyToken"] = self.proxy_token
        if self.passthrough_auth != False:
            out["passthroughAuth"] = self.passthrough_auth
        if self.auto_compact_window != 0:
            out["autoCompactWindow"] = self.auto_compact_window
        if self.record_requests != False:
            out["recordRequests"] = self.record_requests
        if self.append_system_prompt != "":
            out["appendSystemPrompt"] = self.append_system_prompt
        if self.extra_args:
            out["extraArgs"] = [x for x in self.extra_args]
        if self.mcp_token != "":
            out["mcpToken"] = self.mcp_token
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ClaudeParams":
        obj = cls()
        _v = _d.get("model")
        if _v is not None:
            obj.model = _v
        _v = _d.get("resumeSession")
        if _v is not None:
            obj.resume_session = _v
        _v = _d.get("permissionMode")
        if _v is not None:
            obj.permission_mode = _v
        _v = _d.get("proxyUrl")
        if _v is not None:
            obj.proxy_url = _v
        _v = _d.get("proxyToken")
        if _v is not None:
            obj.proxy_token = _v
        _v = _d.get("passthroughAuth")
        if _v is not None:
            obj.passthrough_auth = _v
        _v = _d.get("autoCompactWindow")
        if _v is not None:
            obj.auto_compact_window = _int_in(_v)
        _v = _d.get("recordRequests")
        if _v is not None:
            obj.record_requests = _v
        _v = _d.get("appendSystemPrompt")
        if _v is not None:
            obj.append_system_prompt = _v
        _v = _d.get("extraArgs")
        if _v is not None:
            obj.extra_args = [x for x in _v]
        _v = _d.get("mcpToken")
        if _v is not None:
            obj.mcp_token = _v
        return obj

@dataclasses.dataclass
class ScriptParams:
    repo: str = ""
    script: str = ""
    modules: list[str] = dataclasses.field(default_factory=list)
    args: list[str] = dataclasses.field(default_factory=list)
    env: dict[str, str] = dataclasses.field(default_factory=dict)
    child_secret: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.repo != "":
            out["repo"] = self.repo
        if self.script != "":
            out["script"] = self.script
        if self.modules:
            out["modules"] = [x for x in self.modules]
        if self.args:
            out["args"] = [x for x in self.args]
        if self.env:
            out["env"] = dict((k, v) for k, v in self.env.items())
        if self.child_secret != "":
            out["childSecret"] = self.child_secret
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ScriptParams":
        obj = cls()
        _v = _d.get("repo")
        if _v is not None:
            obj.repo = _v
        _v = _d.get("script")
        if _v is not None:
            obj.script = _v
        _v = _d.get("modules")
        if _v is not None:
            obj.modules = [x for x in _v]
        _v = _d.get("args")
        if _v is not None:
            obj.args = [x for x in _v]
        _v = _d.get("env")
        if _v is not None:
            obj.env = {k: v for k, v in _v.items()}
        _v = _d.get("childSecret")
        if _v is not None:
            obj.child_secret = _v
        return obj

@dataclasses.dataclass
class ChildSpec:
    kind: str = "KIND_UNSPECIFIED"
    claude: Optional[ClaudeParams] = None
    script: Optional[ScriptParams] = None

    def to_dict(self) -> dict:
        out = {}
        if self.kind != "KIND_UNSPECIFIED":
            out["kind"] = self.kind
        if self.claude is not None:
            out["claude"] = self.claude.to_dict()
        if self.script is not None:
            out["script"] = self.script.to_dict()
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ChildSpec":
        obj = cls()
        _v = _d.get("kind")
        if _v is not None:
            obj.kind = _v
        _v = _d.get("claude")
        if _v is not None:
            obj.claude = ClaudeParams.from_dict(_v)
        _v = _d.get("script")
        if _v is not None:
            obj.script = ScriptParams.from_dict(_v)
        return obj

@dataclasses.dataclass
class RestartRequest:
    spec: Optional[ChildSpec] = None
    grace_ms: int = 0

    def to_dict(self) -> dict:
        out = {}
        if self.spec is not None:
            out["spec"] = self.spec.to_dict()
        if self.grace_ms != 0:
            out["graceMs"] = self.grace_ms
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "RestartRequest":
        obj = cls()
        _v = _d.get("spec")
        if _v is not None:
            obj.spec = ChildSpec.from_dict(_v)
        _v = _d.get("graceMs")
        if _v is not None:
            obj.grace_ms = _int_in(_v)
        return obj

@dataclasses.dataclass
class RestartResponse:
    pid: int = 0

    def to_dict(self) -> dict:
        out = {}
        if self.pid != 0:
            out["pid"] = self.pid
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "RestartResponse":
        obj = cls()
        _v = _d.get("pid")
        if _v is not None:
            obj.pid = _int_in(_v)
        return obj

@dataclasses.dataclass
class ShutdownRequest:
    grace_ms: int = 0

    def to_dict(self) -> dict:
        out = {}
        if self.grace_ms != 0:
            out["graceMs"] = self.grace_ms
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ShutdownRequest":
        obj = cls()
        _v = _d.get("graceMs")
        if _v is not None:
            obj.grace_ms = _int_in(_v)
        return obj

@dataclasses.dataclass
class ShutdownResponse:
    exit_code: int = 0
    signal: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.exit_code != 0:
            out["exitCode"] = self.exit_code
        if self.signal != "":
            out["signal"] = self.signal
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ShutdownResponse":
        obj = cls()
        _v = _d.get("exitCode")
        if _v is not None:
            obj.exit_code = _int_in(_v)
        _v = _d.get("signal")
        if _v is not None:
            obj.signal = _v
        return obj

@dataclasses.dataclass
class HealthRequest:
    pass

    def to_dict(self) -> dict:
        out = {}
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "HealthRequest":
        obj = cls()
        return obj

@dataclasses.dataclass
class HealthResponse:
    pid: int = 0
    running: bool = False

    def to_dict(self) -> dict:
        out = {}
        if self.pid != 0:
            out["pid"] = self.pid
        if self.running != False:
            out["running"] = self.running
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "HealthResponse":
        obj = cls()
        _v = _d.get("pid")
        if _v is not None:
            obj.pid = _int_in(_v)
        _v = _d.get("running")
        if _v is not None:
            obj.running = _v
        return obj



def _b64_out(value: bytes) -> str:
    """bytes → base64 with padding, the protobuf JSON encoding."""
    return base64.b64encode(value).decode("ascii")


def _b64_in(value) -> bytes:
    """base64 → bytes, accepting standard and URL-safe alphabets and any
    padding, exactly as the protobuf JSON decoder must."""
    if not isinstance(value, str):
        raise TypeError("expected base64 string for a bytes field")
    normalized = value.replace("-", "+").replace("_", "/")
    if len(normalized) % 4:
        normalized += "=" * (4 - len(normalized) % 4)
    try:
        return base64.b64decode(normalized, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise ValueError("invalid base64 in bytes field") from exc


def _int_in(value) -> int:
    """A wire integer → int. 64-bit integers travel as strings; 32-bit ones
    as numbers. Both spellings are accepted for either."""
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str):
        try:
            return int(value)
        except ValueError:
            return int(float(value))
    raise TypeError("expected an integer (number or string) on the wire")


def _float_out(value: float):
    """A wire float: the number itself, except non-finite values, which the
    protobuf JSON encoding spells as strings."""
    if math.isnan(value):
        return "NaN"
    if math.isinf(value):
        return "Infinity" if value > 0 else "-Infinity"
    return value


def _float_in(value) -> float:
    """A wire float → Python float, accepting the non-finite strings too."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    if isinstance(value, str):
        if value == "NaN":
            return math.nan
        if value == "Infinity":
            return math.inf
        if value == "-Infinity":
            return -math.inf
        return float(value)
    raise TypeError("expected a number (or non-finite string) on the wire")
