"""Generated by protoc-gen-rafikipy from rafiki/v1/event.proto — do not edit.

Regenerate with make proto. The classes speak the Connect JSON codec:
lowerCamelCase keys, enums as their proto names, 64-bit integers as strings
(decoded from strings or numbers too), bytes as base64. A dataclass field
whose proto field is optional or belongs to a oneof is Optional[...] = None.
"""
from __future__ import annotations

import base64
import binascii
import dataclasses
import math
from typing import Optional

class StopReason:
    STOP_REASON_UNSPECIFIED = "STOP_REASON_UNSPECIFIED"
    STOP_REASON_END_TURN = "STOP_REASON_END_TURN"
    STOP_REASON_MAX_TOKENS = "STOP_REASON_MAX_TOKENS"
    STOP_REASON_TOOL_USE = "STOP_REASON_TOOL_USE"
    STOP_REASON_STOP_SEQUENCE = "STOP_REASON_STOP_SEQUENCE"
    STOP_REASON_REFUSAL = "STOP_REASON_REFUSAL"
    STOP_REASON_ERROR = "STOP_REASON_ERROR"

@dataclasses.dataclass
class Usage:
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
    cache_read_tokens: Optional[int] = None
    cache_write_tokens: Optional[int] = None
    reasoning_tokens: Optional[int] = None

    def to_dict(self) -> dict:
        out = {}
        if self.input_tokens is not None:
            out["inputTokens"] = str(self.input_tokens)
        if self.output_tokens is not None:
            out["outputTokens"] = str(self.output_tokens)
        if self.cache_read_tokens is not None:
            out["cacheReadTokens"] = str(self.cache_read_tokens)
        if self.cache_write_tokens is not None:
            out["cacheWriteTokens"] = str(self.cache_write_tokens)
        if self.reasoning_tokens is not None:
            out["reasoningTokens"] = str(self.reasoning_tokens)
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "Usage":
        obj = cls()
        _v = _d.get("inputTokens")
        if _v is not None:
            obj.input_tokens = _int_in(_v)
        _v = _d.get("outputTokens")
        if _v is not None:
            obj.output_tokens = _int_in(_v)
        _v = _d.get("cacheReadTokens")
        if _v is not None:
            obj.cache_read_tokens = _int_in(_v)
        _v = _d.get("cacheWriteTokens")
        if _v is not None:
            obj.cache_write_tokens = _int_in(_v)
        _v = _d.get("reasoningTokens")
        if _v is not None:
            obj.reasoning_tokens = _int_in(_v)
        return obj

@dataclasses.dataclass
class TextBlock:
    text: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.text != "":
            out["text"] = self.text
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "TextBlock":
        obj = cls()
        _v = _d.get("text")
        if _v is not None:
            obj.text = _v
        return obj

@dataclasses.dataclass
class ThinkingBlock:
    thinking: str = ""
    signature: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.thinking != "":
            out["thinking"] = self.thinking
        if self.signature != "":
            out["signature"] = self.signature
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ThinkingBlock":
        obj = cls()
        _v = _d.get("thinking")
        if _v is not None:
            obj.thinking = _v
        _v = _d.get("signature")
        if _v is not None:
            obj.signature = _v
        return obj

@dataclasses.dataclass
class ToolUseBlock:
    id: str = ""
    name: str = ""
    input_json: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.id != "":
            out["id"] = self.id
        if self.name != "":
            out["name"] = self.name
        if self.input_json != "":
            out["inputJson"] = self.input_json
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ToolUseBlock":
        obj = cls()
        _v = _d.get("id")
        if _v is not None:
            obj.id = _v
        _v = _d.get("name")
        if _v is not None:
            obj.name = _v
        _v = _d.get("inputJson")
        if _v is not None:
            obj.input_json = _v
        return obj

@dataclasses.dataclass
class ImageBlock:
    media_type: str = ""
    data: bytes = b""

    def to_dict(self) -> dict:
        out = {}
        if self.media_type != "":
            out["mediaType"] = self.media_type
        if self.data != b"":
            out["data"] = _b64_out(self.data)
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ImageBlock":
        obj = cls()
        _v = _d.get("mediaType")
        if _v is not None:
            obj.media_type = _v
        _v = _d.get("data")
        if _v is not None:
            obj.data = _b64_in(_v)
        return obj

@dataclasses.dataclass
class ToolResultBlock:
    tool_use_id: str = ""
    content: list[ContentBlock] = dataclasses.field(default_factory=list)
    is_error: bool = False

    def to_dict(self) -> dict:
        out = {}
        if self.tool_use_id != "":
            out["toolUseId"] = self.tool_use_id
        if self.content:
            out["content"] = [x.to_dict() for x in self.content]
        if self.is_error != False:
            out["isError"] = self.is_error
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ToolResultBlock":
        obj = cls()
        _v = _d.get("toolUseId")
        if _v is not None:
            obj.tool_use_id = _v
        _v = _d.get("content")
        if _v is not None:
            obj.content = [ContentBlock.from_dict(x) for x in _v]
        _v = _d.get("isError")
        if _v is not None:
            obj.is_error = _v
        return obj

@dataclasses.dataclass
class ContentBlock:
    index: int = 0
    text: Optional[TextBlock] = None
    thinking: Optional[ThinkingBlock] = None
    tool_use: Optional[ToolUseBlock] = None
    image: Optional[ImageBlock] = None
    tool_result: Optional[ToolResultBlock] = None

    def to_dict(self) -> dict:
        out = {}
        if self.index != 0:
            out["index"] = self.index
        _set_block = [x for x in (self.text, self.thinking, self.tool_use, self.image, self.tool_result) if x is not None]
        if len(_set_block) > 1:
            raise ValueError("ContentBlock: at most one arm of oneof 'block' may be set")
        if self.text is not None:
            out["text"] = self.text.to_dict()
        if self.thinking is not None:
            out["thinking"] = self.thinking.to_dict()
        if self.tool_use is not None:
            out["toolUse"] = self.tool_use.to_dict()
        if self.image is not None:
            out["image"] = self.image.to_dict()
        if self.tool_result is not None:
            out["toolResult"] = self.tool_result.to_dict()
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ContentBlock":
        obj = cls()
        _v = _d.get("index")
        if _v is not None:
            obj.index = _int_in(_v)
        _v = _d.get("text")
        if _v is not None:
            obj.text = TextBlock.from_dict(_v)
        _v = _d.get("thinking")
        if _v is not None:
            obj.thinking = ThinkingBlock.from_dict(_v)
        _v = _d.get("toolUse")
        if _v is not None:
            obj.tool_use = ToolUseBlock.from_dict(_v)
        _v = _d.get("image")
        if _v is not None:
            obj.image = ImageBlock.from_dict(_v)
        _v = _d.get("toolResult")
        if _v is not None:
            obj.tool_result = ToolResultBlock.from_dict(_v)
        return obj

@dataclasses.dataclass
class UserMessage:
    content: list[ContentBlock] = dataclasses.field(default_factory=list)

    def to_dict(self) -> dict:
        out = {}
        if self.content:
            out["content"] = [x.to_dict() for x in self.content]
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "UserMessage":
        obj = cls()
        _v = _d.get("content")
        if _v is not None:
            obj.content = [ContentBlock.from_dict(x) for x in _v]
        return obj

@dataclasses.dataclass
class AssistantMessage:
    content: list[ContentBlock] = dataclasses.field(default_factory=list)
    stop_reason: str = "STOP_REASON_UNSPECIFIED"
    raw_stop_reason: str = ""
    cost_usd: Optional[float] = None

    def to_dict(self) -> dict:
        out = {}
        if self.content:
            out["content"] = [x.to_dict() for x in self.content]
        if self.stop_reason != "STOP_REASON_UNSPECIFIED":
            out["stopReason"] = self.stop_reason
        if self.raw_stop_reason != "":
            out["rawStopReason"] = self.raw_stop_reason
        if self.cost_usd is not None:
            out["costUsd"] = _float_out(self.cost_usd)
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "AssistantMessage":
        obj = cls()
        _v = _d.get("content")
        if _v is not None:
            obj.content = [ContentBlock.from_dict(x) for x in _v]
        _v = _d.get("stopReason")
        if _v is not None:
            obj.stop_reason = _v
        _v = _d.get("rawStopReason")
        if _v is not None:
            obj.raw_stop_reason = _v
        _v = _d.get("costUsd")
        if _v is not None:
            obj.cost_usd = _float_in(_v)
        return obj

@dataclasses.dataclass
class TurnStart:
    turn_id: str = ""
    model: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.turn_id != "":
            out["turnId"] = self.turn_id
        if self.model != "":
            out["model"] = self.model
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "TurnStart":
        obj = cls()
        _v = _d.get("turnId")
        if _v is not None:
            obj.turn_id = _v
        _v = _d.get("model")
        if _v is not None:
            obj.model = _v
        return obj

@dataclasses.dataclass
class TurnEnd:
    turn_id: str = ""
    stop_reason: str = "STOP_REASON_UNSPECIFIED"
    raw_stop_reason: str = ""
    usage: Optional[Usage] = None
    cost_usd: Optional[float] = None

    def to_dict(self) -> dict:
        out = {}
        if self.turn_id != "":
            out["turnId"] = self.turn_id
        if self.stop_reason != "STOP_REASON_UNSPECIFIED":
            out["stopReason"] = self.stop_reason
        if self.raw_stop_reason != "":
            out["rawStopReason"] = self.raw_stop_reason
        if self.usage is not None:
            out["usage"] = self.usage.to_dict()
        if self.cost_usd is not None:
            out["costUsd"] = _float_out(self.cost_usd)
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "TurnEnd":
        obj = cls()
        _v = _d.get("turnId")
        if _v is not None:
            obj.turn_id = _v
        _v = _d.get("stopReason")
        if _v is not None:
            obj.stop_reason = _v
        _v = _d.get("rawStopReason")
        if _v is not None:
            obj.raw_stop_reason = _v
        _v = _d.get("usage")
        if _v is not None:
            obj.usage = Usage.from_dict(_v)
        _v = _d.get("costUsd")
        if _v is not None:
            obj.cost_usd = _float_in(_v)
        return obj

@dataclasses.dataclass
class ContentBlockDelta:
    turn_id: str = ""
    index: int = 0
    text: Optional[str] = None
    thinking: Optional[str] = None
    input_json: Optional[str] = None

    def to_dict(self) -> dict:
        out = {}
        if self.turn_id != "":
            out["turnId"] = self.turn_id
        if self.index != 0:
            out["index"] = self.index
        _set_delta = [x for x in (self.text, self.thinking, self.input_json) if x is not None]
        if len(_set_delta) > 1:
            raise ValueError("ContentBlockDelta: at most one arm of oneof 'delta' may be set")
        if self.text is not None:
            out["text"] = self.text
        if self.thinking is not None:
            out["thinking"] = self.thinking
        if self.input_json is not None:
            out["inputJson"] = self.input_json
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ContentBlockDelta":
        obj = cls()
        _v = _d.get("turnId")
        if _v is not None:
            obj.turn_id = _v
        _v = _d.get("index")
        if _v is not None:
            obj.index = _int_in(_v)
        _v = _d.get("text")
        if _v is not None:
            obj.text = _v
        _v = _d.get("thinking")
        if _v is not None:
            obj.thinking = _v
        _v = _d.get("inputJson")
        if _v is not None:
            obj.input_json = _v
        return obj

@dataclasses.dataclass
class AgentStatus:
    state: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.state != "":
            out["state"] = self.state
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "AgentStatus":
        obj = cls()
        _v = _d.get("state")
        if _v is not None:
            obj.state = _v
        return obj

@dataclasses.dataclass
class ErrorEvent:
    code: str = ""
    message: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.code != "":
            out["code"] = self.code
        if self.message != "":
            out["message"] = self.message
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ErrorEvent":
        obj = cls()
        _v = _d.get("code")
        if _v is not None:
            obj.code = _v
        _v = _d.get("message")
        if _v is not None:
            obj.message = _v
        return obj

@dataclasses.dataclass
class ToolExecutionStart:
    tool_use_id: str = ""
    name: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.tool_use_id != "":
            out["toolUseId"] = self.tool_use_id
        if self.name != "":
            out["name"] = self.name
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ToolExecutionStart":
        obj = cls()
        _v = _d.get("toolUseId")
        if _v is not None:
            obj.tool_use_id = _v
        _v = _d.get("name")
        if _v is not None:
            obj.name = _v
        return obj

@dataclasses.dataclass
class ToolExecutionEnd:
    tool_use_id: str = ""
    duration_ms: int = 0
    is_error: bool = False

    def to_dict(self) -> dict:
        out = {}
        if self.tool_use_id != "":
            out["toolUseId"] = self.tool_use_id
        if self.duration_ms != 0:
            out["durationMs"] = str(self.duration_ms)
        if self.is_error != False:
            out["isError"] = self.is_error
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ToolExecutionEnd":
        obj = cls()
        _v = _d.get("toolUseId")
        if _v is not None:
            obj.tool_use_id = _v
        _v = _d.get("durationMs")
        if _v is not None:
            obj.duration_ms = _int_in(_v)
        _v = _d.get("isError")
        if _v is not None:
            obj.is_error = _v
        return obj

@dataclasses.dataclass
class Retry:
    attempt: int = 0
    will_retry: bool = False
    reason: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.attempt != 0:
            out["attempt"] = self.attempt
        if self.will_retry != False:
            out["willRetry"] = self.will_retry
        if self.reason != "":
            out["reason"] = self.reason
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "Retry":
        obj = cls()
        _v = _d.get("attempt")
        if _v is not None:
            obj.attempt = _int_in(_v)
        _v = _d.get("willRetry")
        if _v is not None:
            obj.will_retry = _v
        _v = _d.get("reason")
        if _v is not None:
            obj.reason = _v
        return obj

@dataclasses.dataclass
class ChildSpawned:
    child_id: str = ""
    parent_id: str = ""
    name: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.child_id != "":
            out["childId"] = self.child_id
        if self.parent_id != "":
            out["parentId"] = self.parent_id
        if self.name != "":
            out["name"] = self.name
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ChildSpawned":
        obj = cls()
        _v = _d.get("childId")
        if _v is not None:
            obj.child_id = _v
        _v = _d.get("parentId")
        if _v is not None:
            obj.parent_id = _v
        _v = _d.get("name")
        if _v is not None:
            obj.name = _v
        return obj

@dataclasses.dataclass
class ChildExited:
    child_id: str = ""
    exit_code: Optional[int] = None
    signal: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.child_id != "":
            out["childId"] = self.child_id
        if self.exit_code is not None:
            out["exitCode"] = self.exit_code
        if self.signal != "":
            out["signal"] = self.signal
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ChildExited":
        obj = cls()
        _v = _d.get("childId")
        if _v is not None:
            obj.child_id = _v
        _v = _d.get("exitCode")
        if _v is not None:
            obj.exit_code = _int_in(_v)
        _v = _d.get("signal")
        if _v is not None:
            obj.signal = _v
        return obj

@dataclasses.dataclass
class CompactionBoundary:
    trigger: str = ""
    pre_tokens: Optional[int] = None
    post_tokens: Optional[int] = None

    def to_dict(self) -> dict:
        out = {}
        if self.trigger != "":
            out["trigger"] = self.trigger
        if self.pre_tokens is not None:
            out["preTokens"] = self.pre_tokens
        if self.post_tokens is not None:
            out["postTokens"] = self.post_tokens
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "CompactionBoundary":
        obj = cls()
        _v = _d.get("trigger")
        if _v is not None:
            obj.trigger = _v
        _v = _d.get("preTokens")
        if _v is not None:
            obj.pre_tokens = _int_in(_v)
        _v = _d.get("postTokens")
        if _v is not None:
            obj.post_tokens = _int_in(_v)
        return obj

@dataclasses.dataclass
class ScriptReport:
    kind: str = ""
    data_json: str = ""

    def to_dict(self) -> dict:
        out = {}
        if self.kind != "":
            out["kind"] = self.kind
        if self.data_json != "":
            out["dataJson"] = self.data_json
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "ScriptReport":
        obj = cls()
        _v = _d.get("kind")
        if _v is not None:
            obj.kind = _v
        _v = _d.get("dataJson")
        if _v is not None:
            obj.data_json = _v
        return obj

@dataclasses.dataclass
class Event:
    child_id: str = ""
    ordinal: Optional[int] = None
    ts_unix_ms: int = 0
    user_message: Optional[UserMessage] = None
    assistant_message: Optional[AssistantMessage] = None
    turn_start: Optional[TurnStart] = None
    content_block_delta: Optional[ContentBlockDelta] = None
    turn_end: Optional[TurnEnd] = None
    agent_status: Optional[AgentStatus] = None
    error: Optional[ErrorEvent] = None
    tool_execution_start: Optional[ToolExecutionStart] = None
    tool_execution_end: Optional[ToolExecutionEnd] = None
    retry: Optional[Retry] = None
    child_spawned: Optional[ChildSpawned] = None
    child_exited: Optional[ChildExited] = None
    compaction_boundary: Optional[CompactionBoundary] = None
    script_report: Optional[ScriptReport] = None

    def to_dict(self) -> dict:
        out = {}
        if self.child_id != "":
            out["childId"] = self.child_id
        if self.ordinal is not None:
            out["ordinal"] = self.ordinal
        if self.ts_unix_ms != 0:
            out["tsUnixMs"] = str(self.ts_unix_ms)
        _set_payload = [x for x in (self.user_message, self.assistant_message, self.turn_start, self.content_block_delta, self.turn_end, self.agent_status, self.error, self.tool_execution_start, self.tool_execution_end, self.retry, self.child_spawned, self.child_exited, self.compaction_boundary, self.script_report) if x is not None]
        if len(_set_payload) > 1:
            raise ValueError("Event: at most one arm of oneof 'payload' may be set")
        if self.user_message is not None:
            out["userMessage"] = self.user_message.to_dict()
        if self.assistant_message is not None:
            out["assistantMessage"] = self.assistant_message.to_dict()
        if self.turn_start is not None:
            out["turnStart"] = self.turn_start.to_dict()
        if self.content_block_delta is not None:
            out["contentBlockDelta"] = self.content_block_delta.to_dict()
        if self.turn_end is not None:
            out["turnEnd"] = self.turn_end.to_dict()
        if self.agent_status is not None:
            out["agentStatus"] = self.agent_status.to_dict()
        if self.error is not None:
            out["error"] = self.error.to_dict()
        if self.tool_execution_start is not None:
            out["toolExecutionStart"] = self.tool_execution_start.to_dict()
        if self.tool_execution_end is not None:
            out["toolExecutionEnd"] = self.tool_execution_end.to_dict()
        if self.retry is not None:
            out["retry"] = self.retry.to_dict()
        if self.child_spawned is not None:
            out["childSpawned"] = self.child_spawned.to_dict()
        if self.child_exited is not None:
            out["childExited"] = self.child_exited.to_dict()
        if self.compaction_boundary is not None:
            out["compactionBoundary"] = self.compaction_boundary.to_dict()
        if self.script_report is not None:
            out["scriptReport"] = self.script_report.to_dict()
        return out
    @classmethod
    def from_dict(cls, _d: dict) -> "Event":
        obj = cls()
        _v = _d.get("childId")
        if _v is not None:
            obj.child_id = _v
        _v = _d.get("ordinal")
        if _v is not None:
            obj.ordinal = _int_in(_v)
        _v = _d.get("tsUnixMs")
        if _v is not None:
            obj.ts_unix_ms = _int_in(_v)
        _v = _d.get("userMessage")
        if _v is not None:
            obj.user_message = UserMessage.from_dict(_v)
        _v = _d.get("assistantMessage")
        if _v is not None:
            obj.assistant_message = AssistantMessage.from_dict(_v)
        _v = _d.get("turnStart")
        if _v is not None:
            obj.turn_start = TurnStart.from_dict(_v)
        _v = _d.get("contentBlockDelta")
        if _v is not None:
            obj.content_block_delta = ContentBlockDelta.from_dict(_v)
        _v = _d.get("turnEnd")
        if _v is not None:
            obj.turn_end = TurnEnd.from_dict(_v)
        _v = _d.get("agentStatus")
        if _v is not None:
            obj.agent_status = AgentStatus.from_dict(_v)
        _v = _d.get("error")
        if _v is not None:
            obj.error = ErrorEvent.from_dict(_v)
        _v = _d.get("toolExecutionStart")
        if _v is not None:
            obj.tool_execution_start = ToolExecutionStart.from_dict(_v)
        _v = _d.get("toolExecutionEnd")
        if _v is not None:
            obj.tool_execution_end = ToolExecutionEnd.from_dict(_v)
        _v = _d.get("retry")
        if _v is not None:
            obj.retry = Retry.from_dict(_v)
        _v = _d.get("childSpawned")
        if _v is not None:
            obj.child_spawned = ChildSpawned.from_dict(_v)
        _v = _d.get("childExited")
        if _v is not None:
            obj.child_exited = ChildExited.from_dict(_v)
        _v = _d.get("compactionBoundary")
        if _v is not None:
            obj.compaction_boundary = CompactionBoundary.from_dict(_v)
        _v = _d.get("scriptReport")
        if _v is not None:
            obj.script_report = ScriptReport.from_dict(_v)
        return obj



def _b64_out(value: bytes) -> str:
    """bytes → base64 with padding, the protobuf JSON encoding."""
    return base64.b64encode(value).decode("ascii")


def _b64_in(value) -> bytes:
    """base64 → bytes, accepting standard and URL-safe alphabets and any
    padding, exactly as the protobuf JSON decoder must."""
    if not isinstance(value, str):
        raise TypeError("expected base64 string for a bytes field")
    normalized = value.replace("-", "+").replace("_", "/")
    if len(normalized) % 4:
        normalized += "=" * (4 - len(normalized) % 4)
    try:
        return base64.b64decode(normalized, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise ValueError("invalid base64 in bytes field") from exc


def _int_in(value) -> int:
    """A wire integer → int. 64-bit integers travel as strings; 32-bit ones
    as numbers. Both spellings are accepted for either."""
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str):
        try:
            return int(value)
        except ValueError:
            return int(float(value))
    raise TypeError("expected an integer (number or string) on the wire")


def _float_out(value: float):
    """A wire float: the number itself, except non-finite values, which the
    protobuf JSON encoding spells as strings."""
    if math.isnan(value):
        return "NaN"
    if math.isinf(value):
        return "Infinity" if value > 0 else "-Infinity"
    return value


def _float_in(value) -> float:
    """A wire float → Python float, accepting the non-finite strings too."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    if isinstance(value, str):
        if value == "NaN":
            return math.nan
        if value == "Infinity":
            return math.inf
        if value == "-Infinity":
            return -math.inf
        return float(value)
    raise TypeError("expected a number (or non-finite string) on the wire")
