// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: rafiki/admin/v1/admin.proto

package adminpb

import (
	darajapb "go.graveland.dev/rafiki/pkg/darajapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaunchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// child_id is the daemon-stamped id this daraja hosts. It scopes the socket
	// path and is the key the executor tracks the launch under.
	ChildId string `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	// cwd is the working directory for the hosted child.
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// spec is typed rather than argv: the executor and daraja both build the
	// child's command line through pkg/claudeargv, so neither side invents one.
	Spec *darajapb.ChildSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// dial_addr is a host:port or a Unix socket path that the daraja dials back
	// to the rafikid that asked for it. Phase 1b-i shipped socket on the response
	// (field 3) as a direct-connect handle; 1b-ii replaces that with a reverse
	// dial whose address arrives here on the request.
	DialAddr string `protobuf:"bytes,4,opt,name=dial_addr,json=dialAddr,proto3" json:"dial_addr,omitempty"`
	// ticket is a one-shot credential the daraja presents on connect. It must not
	// travel in argv because every process on the machine can read it via ps —
	// arrive instead by environment (set from the server). Replaced by a durable
	// credential on first successful hello.
	Ticket        string `protobuf:"bytes,5,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_rafiki_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *LaunchRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *LaunchRequest) GetSpec() *darajapb.ChildSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *LaunchRequest) GetDialAddr() string {
	if x != nil {
		return x.DialAddr
	}
	return ""
}

func (x *LaunchRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type LaunchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pid of the daraja process.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// pgid is the process GROUP that daraja leads and its child joins. This is
	// the reaping handle, and unlike a pid it is stable for the child's whole
	// life: restarts stay in the group, and the group outlives daraja itself, so
	// it still reaches a claude orphaned by a SIGKILLed daraja.
	Pgid          int32 `protobuf:"varint,2,opt,name=pgid,proto3" json:"pgid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_rafiki_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LaunchResponse) GetPgid() int32 {
	if x != nil {
		return x.Pgid
	}
	return 0
}

type ReapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// child_id names a launch this executor is still tracking. It is deliberately
	// NOT a bare pgid: a process group id is recycled once its group empties, so
	// signalling a number supplied by a peer could reach an unrelated group.
	ChildId string `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	// grace_ms between SIGTERM and SIGKILL. Zero means the server default.
	GraceMs       int32 `protobuf:"varint,2,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReapRequest) Reset() {
	*x = ReapRequest{}
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapRequest) ProtoMessage() {}

func (x *ReapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapRequest.ProtoReflect.Descriptor instead.
func (*ReapRequest) Descriptor() ([]byte, []int) {
	return file_rafiki_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ReapRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *ReapRequest) GetGraceMs() int32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type ReapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reaped is false when child_id named no tracked launch, which is the normal
	// answer for something already gone. Reaping is idempotent.
	Reaped        bool `protobuf:"varint,1,opt,name=reaped,proto3" json:"reaped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReapResponse) Reset() {
	*x = ReapResponse{}
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapResponse) ProtoMessage() {}

func (x *ReapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rafiki_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapResponse.ProtoReflect.Descriptor instead.
func (*ReapResponse) Descriptor() ([]byte, []int) {
	return file_rafiki_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ReapResponse) GetReaped() bool {
	if x != nil {
		return x.Reaped
	}
	return false
}

var File_rafiki_admin_v1_admin_proto protoreflect.FileDescriptor

const file_rafiki_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1brafiki/admin/v1/admin.proto\x12\x0frafiki.admin.v1\x1a\x1drafiki/daraja/v1/daraja.proto\"\xa2\x01\n" +
	"\rLaunchRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12/\n" +
	"\x04spec\x18\x03 \x01(\v2\x1b.rafiki.daraja.v1.ChildSpecR\x04spec\x12\x1b\n" +
	"\tdial_addr\x18\x04 \x01(\tR\bdialAddr\x12\x16\n" +
	"\x06ticket\x18\x05 \x01(\tR\x06ticket\"D\n" +
	"\x0eLaunchResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04pgid\x18\x02 \x01(\x05R\x04pgidJ\x04\b\x03\x10\x04R\x06socket\"C\n" +
	"\vReapRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12\x19\n" +
	"\bgrace_ms\x18\x02 \x01(\x05R\agraceMs\"&\n" +
	"\fReapResponse\x12\x16\n" +
	"\x06reaped\x18\x01 \x01(\bR\x06reaped2\x9e\x01\n" +
	"\fAdminService\x12I\n" +
	"\x06Launch\x12\x1e.rafiki.admin.v1.LaunchRequest\x1a\x1f.rafiki.admin.v1.LaunchResponse\x12C\n" +
	"\x04Reap\x12\x1c.rafiki.admin.v1.ReapRequest\x1a\x1d.rafiki.admin.v1.ReapResponseB-Z+go.graveland.dev/rafiki/pkg/adminpb;adminpbb\x06proto3"

var (
	file_rafiki_admin_v1_admin_proto_rawDescOnce sync.Once
	file_rafiki_admin_v1_admin_proto_rawDescData []byte
)

func file_rafiki_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_rafiki_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_rafiki_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rafiki_admin_v1_admin_proto_rawDesc), len(file_rafiki_admin_v1_admin_proto_rawDesc)))
	})
	return file_rafiki_admin_v1_admin_proto_rawDescData
}

var file_rafiki_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rafiki_admin_v1_admin_proto_goTypes = []any{
	(*LaunchRequest)(nil),      // 0: rafiki.admin.v1.LaunchRequest
	(*LaunchResponse)(nil),     // 1: rafiki.admin.v1.LaunchResponse
	(*ReapRequest)(nil),        // 2: rafiki.admin.v1.ReapRequest
	(*ReapResponse)(nil),       // 3: rafiki.admin.v1.ReapResponse
	(*darajapb.ChildSpec)(nil), // 4: rafiki.daraja.v1.ChildSpec
}
var file_rafiki_admin_v1_admin_proto_depIdxs = []int32{
	4, // 0: rafiki.admin.v1.LaunchRequest.spec:type_name -> rafiki.daraja.v1.ChildSpec
	0, // 1: rafiki.admin.v1.AdminService.Launch:input_type -> rafiki.admin.v1.LaunchRequest
	2, // 2: rafiki.admin.v1.AdminService.Reap:input_type -> rafiki.admin.v1.ReapRequest
	1, // 3: rafiki.admin.v1.AdminService.Launch:output_type -> rafiki.admin.v1.LaunchResponse
	3, // 4: rafiki.admin.v1.AdminService.Reap:output_type -> rafiki.admin.v1.ReapResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rafiki_admin_v1_admin_proto_init() }
func file_rafiki_admin_v1_admin_proto_init() {
	if File_rafiki_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rafiki_admin_v1_admin_proto_rawDesc), len(file_rafiki_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rafiki_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_rafiki_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_rafiki_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_rafiki_admin_v1_admin_proto = out.File
	file_rafiki_admin_v1_admin_proto_goTypes = nil
	file_rafiki_admin_v1_admin_proto_depIdxs = nil
}
